/* Sokol-Lua example: runs a Lua script with sokol bindings */
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#include "sokol_log.h"
#include "sokol_gl.h"

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* declare luaopen functions from generated bindings */
extern int luaopen_sokol_gfx(lua_State *L);
extern int luaopen_sokol_app(lua_State *L);
extern int luaopen_sokol_glue(lua_State *L);
extern int luaopen_sokol_log(lua_State *L);
extern int luaopen_sokol_time(lua_State *L);
extern int luaopen_sokol_gl(lua_State *L);

static lua_State *L = NULL;

/* Create a vertex buffer from a Lua table of floats
   usage_type: 0=immutable, 1=dynamic, 2=stream */
static int l_make_vertex_buffer(lua_State *L) {
    luaL_checktype(L, 1, LUA_TTABLE);
    int usage_type = (int)luaL_optinteger(L, 2, 0); /* 0=immutable, 1=dynamic, 2=stream */

    /* Get table length */
    lua_len(L, 1);
    int len = (int)lua_tointeger(L, -1);
    lua_pop(L, 1);

    /* Allocate and fill float array */
    float* data = (float*)malloc(len * sizeof(float));
    for (int i = 0; i < len; i++) {
        lua_rawgeti(L, 1, i + 1);
        data[i] = (float)lua_tonumber(L, -1);
        lua_pop(L, 1);
    }

    /* Create buffer */
    sg_buffer_desc desc = {0};
    desc.size = len * sizeof(float);
    desc.usage.vertex_buffer = true;
    if (usage_type == 0) {
        desc.usage.immutable = true;
        desc.data = (sg_range){ data, len * sizeof(float) };
    } else if (usage_type == 1) {
        desc.usage.dynamic_update = true;
    } else {
        desc.usage.stream_update = true;
    }
    sg_buffer buf = sg_make_buffer(&desc);

    free(data);

    /* Return as userdata */
    sg_buffer* ud = (sg_buffer*)lua_newuserdatauv(L, sizeof(sg_buffer), 0);
    *ud = buf;
    luaL_setmetatable(L, "sokol.Buffer");
    return 1;
}

/* Update a vertex buffer from a Lua table of floats */
static int l_update_buffer(lua_State *L) {
    sg_buffer* buf = (sg_buffer*)luaL_checkudata(L, 1, "sokol.Buffer");
    luaL_checktype(L, 2, LUA_TTABLE);

    lua_len(L, 2);
    int len = (int)lua_tointeger(L, -1);
    lua_pop(L, 1);

    float* data = (float*)malloc(len * sizeof(float));
    for (int i = 0; i < len; i++) {
        lua_rawgeti(L, 2, i + 1);
        data[i] = (float)lua_tonumber(L, -1);
        lua_pop(L, 1);
    }

    sg_update_buffer(*buf, &(sg_range){ data, len * sizeof(float) });
    free(data);
    return 0;
}

/* Load shader from files (generated by sokol-shdc -f bare) */
static int l_load_shader_bytecode(lua_State *L) {
    const char* vs_path = luaL_checkstring(L, 1);
    const char* fs_path = luaL_checkstring(L, 2);

    /* Read vertex shader */
    FILE* vs_file = fopen(vs_path, "rb");
    if (!vs_file) {
        lua_pushnil(L);
        lua_pushfstring(L, "Cannot open VS file: %s", vs_path);
        return 2;
    }
    fseek(vs_file, 0, SEEK_END);
    long vs_size = ftell(vs_file);
    fseek(vs_file, 0, SEEK_SET);
    char* vs_data = (char*)malloc(vs_size + 1);
    fread(vs_data, 1, vs_size, vs_file);
    vs_data[vs_size] = '\0';
    fclose(vs_file);

    /* Read fragment shader */
    FILE* fs_file = fopen(fs_path, "rb");
    if (!fs_file) {
        free(vs_data);
        lua_pushnil(L);
        lua_pushfstring(L, "Cannot open FS file: %s", fs_path);
        return 2;
    }
    fseek(fs_file, 0, SEEK_END);
    long fs_size = ftell(fs_file);
    fseek(fs_file, 0, SEEK_SET);
    char* fs_data = (char*)malloc(fs_size + 1);
    fread(fs_data, 1, fs_size, fs_file);
    fs_data[fs_size] = '\0';
    fclose(fs_file);

    /* Create shader based on backend */
    sg_shader_desc desc = {0};
    sg_backend backend = sg_query_backend();

    if (backend == SG_BACKEND_GLCORE || backend == SG_BACKEND_GLES3) {
        /* GLSL: use source strings */
        desc.vertex_func.source = vs_data;
        desc.fragment_func.source = fs_data;
    } else {
        /* D3D11/Metal/WGPU: use bytecode */
        desc.vertex_func.bytecode = (sg_range){ vs_data, vs_size };
        desc.fragment_func.bytecode = (sg_range){ fs_data, fs_size };
    }

    /* Set vertex attribute semantics for D3D11/Metal */
    if (backend == SG_BACKEND_D3D11) {
        desc.attrs[0].hlsl_sem_name = "TEXCOORD";
        desc.attrs[0].hlsl_sem_index = 0;
        desc.attrs[1].hlsl_sem_name = "TEXCOORD";
        desc.attrs[1].hlsl_sem_index = 1;
    }

    sg_shader shd = sg_make_shader(&desc);

    free(vs_data);
    free(fs_data);

    if (sg_query_shader_state(shd) != SG_RESOURCESTATE_VALID) {
        lua_pushnil(L);
        lua_pushstring(L, "Failed to create shader");
        return 2;
    }

    sg_shader* ud = (sg_shader*)lua_newuserdatauv(L, sizeof(sg_shader), 0);
    *ud = shd;
    luaL_setmetatable(L, "sokol.Shader");
    return 1;
}

/* ---- App callbacks ---- */

static void call_lua(const char *func) {
    lua_getglobal(L, func);
    if (lua_isfunction(L, -1)) {
        if (lua_pcall(L, 0, 0, 0) != LUA_OK) {
            fprintf(stderr, "Lua error in %s: %s\n", func, lua_tostring(L, -1));
            lua_pop(L, 1);
        }
    } else {
        lua_pop(L, 1);
    }
}

static void init(void) {
    sg_setup(&(sg_desc){
        .environment = sglue_environment(),
        .logger.func = slog_func,
    });
    sgl_setup(&(sgl_desc_t){
        .logger.func = slog_func,
    });
    call_lua("init");
}

static void frame(void) {
    call_lua("frame");
}

static void cleanup(void) {
    call_lua("cleanup");
    sgl_shutdown();
    sg_shutdown();
    lua_close(L);
}

static void event(const sapp_event *ev) {
    lua_getglobal(L, "event");
    if (lua_isfunction(L, -1)) {
        /* push event as table */
        lua_newtable(L);
        lua_pushinteger(L, ev->type);
        lua_setfield(L, -2, "type");
        lua_pushinteger(L, ev->key_code);
        lua_setfield(L, -2, "key_code");
        lua_pushnumber(L, ev->mouse_x);
        lua_setfield(L, -2, "mouse_x");
        lua_pushnumber(L, ev->mouse_y);
        lua_setfield(L, -2, "mouse_y");

        if (lua_pcall(L, 1, 0, 0) != LUA_OK) {
            fprintf(stderr, "Lua error in event: %s\n", lua_tostring(L, -1));
            lua_pop(L, 1);
        }
    } else {
        lua_pop(L, 1);
    }
}

sapp_desc sokol_main(int argc, char* argv[]) {
    /* Initialize Lua */
    L = luaL_newstate();
    luaL_openlibs(L);

    /* Register generated sokol modules */
    luaL_requiref(L, "sokol.gfx", luaopen_sokol_gfx, 0);
    lua_pop(L, 1);
    luaL_requiref(L, "sokol.app", luaopen_sokol_app, 0);
    lua_pop(L, 1);
    luaL_requiref(L, "sokol.glue", luaopen_sokol_glue, 0);
    lua_pop(L, 1);
    luaL_requiref(L, "sokol.log", luaopen_sokol_log, 0);
    lua_pop(L, 1);
    luaL_requiref(L, "sokol.time", luaopen_sokol_time, 0);
    lua_pop(L, 1);
    luaL_requiref(L, "sokol.gl", luaopen_sokol_gl, 0);
    lua_pop(L, 1);

    /* Register helper functions in sokol.gfx */
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "loaded");
    lua_getfield(L, -1, "sokol.gfx");
    lua_pushcfunction(L, l_make_vertex_buffer);
    lua_setfield(L, -2, "make_vertex_buffer");
    lua_pushcfunction(L, l_update_buffer);
    lua_setfield(L, -2, "update_buffer");
    lua_pushcfunction(L, l_load_shader_bytecode);
    lua_setfield(L, -2, "load_shader_bytecode");
    lua_pop(L, 3);

    /* Load script */
    const char *script = (argc > 1) ? argv[1] : "main.lua";
    if (luaL_dofile(L, script) != LUA_OK) {
        fprintf(stderr, "Failed to load %s: %s\n", script, lua_tostring(L, -1));
    }

    return (sapp_desc){
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = event,
        .width = 800,
        .height = 600,
        .window_title = "Sokol Lua",
        .logger.func = slog_func,
    };
}
