---@meta
-- LuaCATS type definitions for sokol.gfx
-- Auto-generated, do not edit

---@class gfx
---@field Buffer fun(t?: gfx.Buffer): gfx.Buffer
---@field Image fun(t?: gfx.Image): gfx.Image
---@field Sampler fun(t?: gfx.Sampler): gfx.Sampler
---@field Shader fun(t?: gfx.Shader): gfx.Shader
---@field Pipeline fun(t?: gfx.Pipeline): gfx.Pipeline
---@field View fun(t?: gfx.View): gfx.View
---@field Range fun(t?: gfx.Range): gfx.Range
---@field Color fun(t?: gfx.Color): gfx.Color
---@field PixelformatInfo fun(t?: gfx.PixelformatInfo): gfx.PixelformatInfo
---@field Features fun(t?: gfx.Features): gfx.Features
---@field Limits fun(t?: gfx.Limits): gfx.Limits
---@field ColorAttachmentAction fun(t?: gfx.ColorAttachmentAction): gfx.ColorAttachmentAction
---@field DepthAttachmentAction fun(t?: gfx.DepthAttachmentAction): gfx.DepthAttachmentAction
---@field StencilAttachmentAction fun(t?: gfx.StencilAttachmentAction): gfx.StencilAttachmentAction
---@field PassAction fun(t?: gfx.PassAction): gfx.PassAction
---@field MetalSwapchain fun(t?: gfx.MetalSwapchain): gfx.MetalSwapchain
---@field D3d11Swapchain fun(t?: gfx.D3d11Swapchain): gfx.D3d11Swapchain
---@field WgpuSwapchain fun(t?: gfx.WgpuSwapchain): gfx.WgpuSwapchain
---@field VulkanSwapchain fun(t?: gfx.VulkanSwapchain): gfx.VulkanSwapchain
---@field GlSwapchain fun(t?: gfx.GlSwapchain): gfx.GlSwapchain
---@field Swapchain fun(t?: gfx.Swapchain): gfx.Swapchain
---@field Attachments fun(t?: gfx.Attachments): gfx.Attachments
---@field Pass fun(t?: gfx.Pass): gfx.Pass
---@field Bindings fun(t?: gfx.Bindings): gfx.Bindings
---@field BufferUsage fun(t?: gfx.BufferUsage): gfx.BufferUsage
---@field BufferDesc fun(t?: gfx.BufferDesc): gfx.BufferDesc
---@field ImageUsage fun(t?: gfx.ImageUsage): gfx.ImageUsage
---@field ImageData fun(t?: gfx.ImageData): gfx.ImageData
---@field ImageDesc fun(t?: gfx.ImageDesc): gfx.ImageDesc
---@field SamplerDesc fun(t?: gfx.SamplerDesc): gfx.SamplerDesc
---@field ShaderFunction fun(t?: gfx.ShaderFunction): gfx.ShaderFunction
---@field ShaderVertexAttr fun(t?: gfx.ShaderVertexAttr): gfx.ShaderVertexAttr
---@field GlslShaderUniform fun(t?: gfx.GlslShaderUniform): gfx.GlslShaderUniform
---@field ShaderUniformBlock fun(t?: gfx.ShaderUniformBlock): gfx.ShaderUniformBlock
---@field ShaderTextureView fun(t?: gfx.ShaderTextureView): gfx.ShaderTextureView
---@field ShaderStorageBufferView fun(t?: gfx.ShaderStorageBufferView): gfx.ShaderStorageBufferView
---@field ShaderStorageImageView fun(t?: gfx.ShaderStorageImageView): gfx.ShaderStorageImageView
---@field ShaderView fun(t?: gfx.ShaderView): gfx.ShaderView
---@field ShaderSampler fun(t?: gfx.ShaderSampler): gfx.ShaderSampler
---@field ShaderTextureSamplerPair fun(t?: gfx.ShaderTextureSamplerPair): gfx.ShaderTextureSamplerPair
---@field MtlShaderThreadsPerThreadgroup fun(t?: gfx.MtlShaderThreadsPerThreadgroup): gfx.MtlShaderThreadsPerThreadgroup
---@field ShaderDesc fun(t?: gfx.ShaderDesc): gfx.ShaderDesc
---@field VertexBufferLayoutState fun(t?: gfx.VertexBufferLayoutState): gfx.VertexBufferLayoutState
---@field VertexAttrState fun(t?: gfx.VertexAttrState): gfx.VertexAttrState
---@field VertexLayoutState fun(t?: gfx.VertexLayoutState): gfx.VertexLayoutState
---@field StencilFaceState fun(t?: gfx.StencilFaceState): gfx.StencilFaceState
---@field StencilState fun(t?: gfx.StencilState): gfx.StencilState
---@field DepthState fun(t?: gfx.DepthState): gfx.DepthState
---@field BlendState fun(t?: gfx.BlendState): gfx.BlendState
---@field ColorTargetState fun(t?: gfx.ColorTargetState): gfx.ColorTargetState
---@field PipelineDesc fun(t?: gfx.PipelineDesc): gfx.PipelineDesc
---@field BufferViewDesc fun(t?: gfx.BufferViewDesc): gfx.BufferViewDesc
---@field ImageViewDesc fun(t?: gfx.ImageViewDesc): gfx.ImageViewDesc
---@field TextureViewRange fun(t?: gfx.TextureViewRange): gfx.TextureViewRange
---@field TextureViewDesc fun(t?: gfx.TextureViewDesc): gfx.TextureViewDesc
---@field ViewDesc fun(t?: gfx.ViewDesc): gfx.ViewDesc
---@field TraceHooks fun(t?: gfx.TraceHooks): gfx.TraceHooks
---@field SlotInfo fun(t?: gfx.SlotInfo): gfx.SlotInfo
---@field BufferInfo fun(t?: gfx.BufferInfo): gfx.BufferInfo
---@field ImageInfo fun(t?: gfx.ImageInfo): gfx.ImageInfo
---@field SamplerInfo fun(t?: gfx.SamplerInfo): gfx.SamplerInfo
---@field ShaderInfo fun(t?: gfx.ShaderInfo): gfx.ShaderInfo
---@field PipelineInfo fun(t?: gfx.PipelineInfo): gfx.PipelineInfo
---@field ViewInfo fun(t?: gfx.ViewInfo): gfx.ViewInfo
---@field FrameStatsGl fun(t?: gfx.FrameStatsGl): gfx.FrameStatsGl
---@field FrameStatsD3d11Pass fun(t?: gfx.FrameStatsD3d11Pass): gfx.FrameStatsD3d11Pass
---@field FrameStatsD3d11Pipeline fun(t?: gfx.FrameStatsD3d11Pipeline): gfx.FrameStatsD3d11Pipeline
---@field FrameStatsD3d11Bindings fun(t?: gfx.FrameStatsD3d11Bindings): gfx.FrameStatsD3d11Bindings
---@field FrameStatsD3d11Uniforms fun(t?: gfx.FrameStatsD3d11Uniforms): gfx.FrameStatsD3d11Uniforms
---@field FrameStatsD3d11Draw fun(t?: gfx.FrameStatsD3d11Draw): gfx.FrameStatsD3d11Draw
---@field FrameStatsD3d11 fun(t?: gfx.FrameStatsD3d11): gfx.FrameStatsD3d11
---@field FrameStatsMetalIdpool fun(t?: gfx.FrameStatsMetalIdpool): gfx.FrameStatsMetalIdpool
---@field FrameStatsMetalPipeline fun(t?: gfx.FrameStatsMetalPipeline): gfx.FrameStatsMetalPipeline
---@field FrameStatsMetalBindings fun(t?: gfx.FrameStatsMetalBindings): gfx.FrameStatsMetalBindings
---@field FrameStatsMetalUniforms fun(t?: gfx.FrameStatsMetalUniforms): gfx.FrameStatsMetalUniforms
---@field FrameStatsMetal fun(t?: gfx.FrameStatsMetal): gfx.FrameStatsMetal
---@field FrameStatsWgpuUniforms fun(t?: gfx.FrameStatsWgpuUniforms): gfx.FrameStatsWgpuUniforms
---@field FrameStatsWgpuBindings fun(t?: gfx.FrameStatsWgpuBindings): gfx.FrameStatsWgpuBindings
---@field FrameStatsWgpu fun(t?: gfx.FrameStatsWgpu): gfx.FrameStatsWgpu
---@field FrameStatsVk fun(t?: gfx.FrameStatsVk): gfx.FrameStatsVk
---@field FrameResourceStats fun(t?: gfx.FrameResourceStats): gfx.FrameResourceStats
---@field TotalResourceStats fun(t?: gfx.TotalResourceStats): gfx.TotalResourceStats
---@field TotalStats fun(t?: gfx.TotalStats): gfx.TotalStats
---@field FrameStats fun(t?: gfx.FrameStats): gfx.FrameStats
---@field Stats fun(t?: gfx.Stats): gfx.Stats
---@field EnvironmentDefaults fun(t?: gfx.EnvironmentDefaults): gfx.EnvironmentDefaults
---@field MetalEnvironment fun(t?: gfx.MetalEnvironment): gfx.MetalEnvironment
---@field D3d11Environment fun(t?: gfx.D3d11Environment): gfx.D3d11Environment
---@field WgpuEnvironment fun(t?: gfx.WgpuEnvironment): gfx.WgpuEnvironment
---@field VulkanEnvironment fun(t?: gfx.VulkanEnvironment): gfx.VulkanEnvironment
---@field Environment fun(t?: gfx.Environment): gfx.Environment
---@field CommitListener fun(t?: gfx.CommitListener): gfx.CommitListener
---@field Allocator fun(t?: gfx.Allocator): gfx.Allocator
---@field Logger fun(t?: gfx.Logger): gfx.Logger
---@field D3d11Desc fun(t?: gfx.D3d11Desc): gfx.D3d11Desc
---@field MetalDesc fun(t?: gfx.MetalDesc): gfx.MetalDesc
---@field WgpuDesc fun(t?: gfx.WgpuDesc): gfx.WgpuDesc
---@field VulkanDesc fun(t?: gfx.VulkanDesc): gfx.VulkanDesc
---@field Desc fun(t?: gfx.Desc): gfx.Desc
---@field D3d11BufferInfo fun(t?: gfx.D3d11BufferInfo): gfx.D3d11BufferInfo
---@field D3d11ImageInfo fun(t?: gfx.D3d11ImageInfo): gfx.D3d11ImageInfo
---@field D3d11SamplerInfo fun(t?: gfx.D3d11SamplerInfo): gfx.D3d11SamplerInfo
---@field D3d11ShaderInfo fun(t?: gfx.D3d11ShaderInfo): gfx.D3d11ShaderInfo
---@field D3d11PipelineInfo fun(t?: gfx.D3d11PipelineInfo): gfx.D3d11PipelineInfo
---@field D3d11ViewInfo fun(t?: gfx.D3d11ViewInfo): gfx.D3d11ViewInfo
---@field MtlBufferInfo fun(t?: gfx.MtlBufferInfo): gfx.MtlBufferInfo
---@field MtlImageInfo fun(t?: gfx.MtlImageInfo): gfx.MtlImageInfo
---@field MtlSamplerInfo fun(t?: gfx.MtlSamplerInfo): gfx.MtlSamplerInfo
---@field MtlShaderInfo fun(t?: gfx.MtlShaderInfo): gfx.MtlShaderInfo
---@field MtlPipelineInfo fun(t?: gfx.MtlPipelineInfo): gfx.MtlPipelineInfo
---@field WgpuBufferInfo fun(t?: gfx.WgpuBufferInfo): gfx.WgpuBufferInfo
---@field WgpuImageInfo fun(t?: gfx.WgpuImageInfo): gfx.WgpuImageInfo
---@field WgpuSamplerInfo fun(t?: gfx.WgpuSamplerInfo): gfx.WgpuSamplerInfo
---@field WgpuShaderInfo fun(t?: gfx.WgpuShaderInfo): gfx.WgpuShaderInfo
---@field WgpuPipelineInfo fun(t?: gfx.WgpuPipelineInfo): gfx.WgpuPipelineInfo
---@field WgpuViewInfo fun(t?: gfx.WgpuViewInfo): gfx.WgpuViewInfo
---@field GlBufferInfo fun(t?: gfx.GlBufferInfo): gfx.GlBufferInfo
---@field GlImageInfo fun(t?: gfx.GlImageInfo): gfx.GlImageInfo
---@field GlSamplerInfo fun(t?: gfx.GlSamplerInfo): gfx.GlSamplerInfo
---@field GlShaderInfo fun(t?: gfx.GlShaderInfo): gfx.GlShaderInfo
---@field GlViewInfo fun(t?: gfx.GlViewInfo): gfx.GlViewInfo
local gfx = {}

---@enum gfx.Backend
gfx.Backend = {
    GLCORE = 0,
    GLES3 = 1,
    D3D11 = 2,
    METAL_IOS = 3,
    METAL_MACOS = 4,
    METAL_SIMULATOR = 5,
    WGPU = 6,
    VULKAN = 7,
    DUMMY = 8,
}

---@enum gfx.PixelFormat
gfx.PixelFormat = {
    DEFAULT = 0,
    NONE = 1,
    R8 = 2,
    R8SN = 3,
    R8UI = 4,
    R8SI = 5,
    R16 = 6,
    R16SN = 7,
    R16UI = 8,
    R16SI = 9,
    R16F = 10,
    RG8 = 11,
    RG8SN = 12,
    RG8UI = 13,
    RG8SI = 14,
    R32UI = 15,
    R32SI = 16,
    R32F = 17,
    RG16 = 18,
    RG16SN = 19,
    RG16UI = 20,
    RG16SI = 21,
    RG16F = 22,
    RGBA8 = 23,
    SRGB8A8 = 24,
    RGBA8SN = 25,
    RGBA8UI = 26,
    RGBA8SI = 27,
    BGRA8 = 28,
    RGB10A2 = 29,
    RG11B10F = 30,
    RGB9E5 = 31,
    RG32UI = 32,
    RG32SI = 33,
    RG32F = 34,
    RGBA16 = 35,
    RGBA16SN = 36,
    RGBA16UI = 37,
    RGBA16SI = 38,
    RGBA16F = 39,
    RGBA32UI = 40,
    RGBA32SI = 41,
    RGBA32F = 42,
    DEPTH = 43,
    DEPTH_STENCIL = 44,
    BC1_RGBA = 45,
    BC2_RGBA = 46,
    BC3_RGBA = 47,
    BC3_SRGBA = 48,
    BC4_R = 49,
    BC4_RSN = 50,
    BC5_RG = 51,
    BC5_RGSN = 52,
    BC6H_RGBF = 53,
    BC6H_RGBUF = 54,
    BC7_RGBA = 55,
    BC7_SRGBA = 56,
    ETC2_RGB8 = 57,
    ETC2_SRGB8 = 58,
    ETC2_RGB8A1 = 59,
    ETC2_RGBA8 = 60,
    ETC2_SRGB8A8 = 61,
    EAC_R11 = 62,
    EAC_R11SN = 63,
    EAC_RG11 = 64,
    EAC_RG11SN = 65,
    ASTC_4x4_RGBA = 66,
    ASTC_4x4_SRGBA = 67,
    NUM = 68,
}

---@enum gfx.ResourceState
gfx.ResourceState = {
    INITIAL = 0,
    ALLOC = 1,
    VALID = 2,
    FAILED = 3,
    INVALID = 4,
}

---@enum gfx.IndexType
gfx.IndexType = {
    DEFAULT = 0,
    NONE = 1,
    UINT16 = 2,
    UINT32 = 3,
    NUM = 4,
}

---@enum gfx.ImageType
gfx.ImageType = {
    DEFAULT = 0,
    2D = 1,
    CUBE = 2,
    3D = 3,
    ARRAY = 4,
    NUM = 5,
}

---@enum gfx.ImageSampleType
gfx.ImageSampleType = {
    DEFAULT = 0,
    FLOAT = 1,
    DEPTH = 2,
    SINT = 3,
    UINT = 4,
    UNFILTERABLE_FLOAT = 5,
    NUM = 6,
}

---@enum gfx.SamplerType
gfx.SamplerType = {
    DEFAULT = 0,
    FILTERING = 1,
    NONFILTERING = 2,
    COMPARISON = 3,
    NUM = 4,
}

---@enum gfx.PrimitiveType
gfx.PrimitiveType = {
    DEFAULT = 0,
    POINTS = 1,
    LINES = 2,
    LINE_STRIP = 3,
    TRIANGLES = 4,
    TRIANGLE_STRIP = 5,
    NUM = 6,
}

---@enum gfx.Filter
gfx.Filter = {
    DEFAULT = 0,
    NEAREST = 1,
    LINEAR = 2,
    NUM = 3,
}

---@enum gfx.Wrap
gfx.Wrap = {
    DEFAULT = 0,
    REPEAT = 1,
    CLAMP_TO_EDGE = 2,
    CLAMP_TO_BORDER = 3,
    MIRRORED_REPEAT = 4,
    NUM = 5,
}

---@enum gfx.BorderColor
gfx.BorderColor = {
    DEFAULT = 0,
    TRANSPARENT_BLACK = 1,
    OPAQUE_BLACK = 2,
    OPAQUE_WHITE = 3,
    NUM = 4,
}

---@enum gfx.VertexFormat
gfx.VertexFormat = {
    INVALID = 0,
    FLOAT = 1,
    FLOAT2 = 2,
    FLOAT3 = 3,
    FLOAT4 = 4,
    INT = 5,
    INT2 = 6,
    INT3 = 7,
    INT4 = 8,
    UINT = 9,
    UINT2 = 10,
    UINT3 = 11,
    UINT4 = 12,
    BYTE4 = 13,
    BYTE4N = 14,
    UBYTE4 = 15,
    UBYTE4N = 16,
    SHORT2 = 17,
    SHORT2N = 18,
    USHORT2 = 19,
    USHORT2N = 20,
    SHORT4 = 21,
    SHORT4N = 22,
    USHORT4 = 23,
    USHORT4N = 24,
    UINT10_N2 = 25,
    HALF2 = 26,
    HALF4 = 27,
    NUM = 28,
}

---@enum gfx.VertexStep
gfx.VertexStep = {
    DEFAULT = 0,
    PER_VERTEX = 1,
    PER_INSTANCE = 2,
    NUM = 3,
}

---@enum gfx.UniformType
gfx.UniformType = {
    INVALID = 0,
    FLOAT = 1,
    FLOAT2 = 2,
    FLOAT3 = 3,
    FLOAT4 = 4,
    INT = 5,
    INT2 = 6,
    INT3 = 7,
    INT4 = 8,
    MAT4 = 9,
    NUM = 10,
}

---@enum gfx.UniformLayout
gfx.UniformLayout = {
    DEFAULT = 0,
    NATIVE = 1,
    STD140 = 2,
    NUM = 3,
}

---@enum gfx.CullMode
gfx.CullMode = {
    DEFAULT = 0,
    NONE = 1,
    FRONT = 2,
    BACK = 3,
    NUM = 4,
}

---@enum gfx.FaceWinding
gfx.FaceWinding = {
    DEFAULT = 0,
    CCW = 1,
    CW = 2,
    NUM = 3,
}

---@enum gfx.CompareFunc
gfx.CompareFunc = {
    DEFAULT = 0,
    NEVER = 1,
    LESS = 2,
    EQUAL = 3,
    LESS_EQUAL = 4,
    GREATER = 5,
    NOT_EQUAL = 6,
    GREATER_EQUAL = 7,
    ALWAYS = 8,
    NUM = 9,
}

---@enum gfx.StencilOp
gfx.StencilOp = {
    DEFAULT = 0,
    KEEP = 1,
    ZERO = 2,
    REPLACE = 3,
    INCR_CLAMP = 4,
    DECR_CLAMP = 5,
    INVERT = 6,
    INCR_WRAP = 7,
    DECR_WRAP = 8,
    NUM = 9,
}

---@enum gfx.BlendFactor
gfx.BlendFactor = {
    DEFAULT = 0,
    ZERO = 1,
    ONE = 2,
    SRC_COLOR = 3,
    ONE_MINUS_SRC_COLOR = 4,
    SRC_ALPHA = 5,
    ONE_MINUS_SRC_ALPHA = 6,
    DST_COLOR = 7,
    ONE_MINUS_DST_COLOR = 8,
    DST_ALPHA = 9,
    ONE_MINUS_DST_ALPHA = 10,
    SRC_ALPHA_SATURATED = 11,
    BLEND_COLOR = 12,
    ONE_MINUS_BLEND_COLOR = 13,
    BLEND_ALPHA = 14,
    ONE_MINUS_BLEND_ALPHA = 15,
    NUM = 16,
}

---@enum gfx.BlendOp
gfx.BlendOp = {
    DEFAULT = 0,
    ADD = 1,
    SUBTRACT = 2,
    REVERSE_SUBTRACT = 3,
    MIN = 4,
    MAX = 5,
    NUM = 6,
}

---@enum gfx.ColorMask
gfx.ColorMask = {
    DEFAULT = 0,
    NONE = 16,
    R = 1,
    G = 2,
    RG = 3,
    B = 4,
    RB = 5,
    GB = 6,
    RGB = 7,
    A = 8,
    RA = 9,
    GA = 10,
    RGA = 11,
    BA = 12,
    RBA = 13,
    GBA = 14,
    RGBA = 15,
}

---@enum gfx.LoadAction
gfx.LoadAction = {
    DEFAULT = 0,
    CLEAR = 1,
    LOAD = 2,
    DONTCARE = 3,
}

---@enum gfx.StoreAction
gfx.StoreAction = {
    DEFAULT = 0,
    STORE = 1,
    DONTCARE = 2,
}

---@enum gfx.ViewType
gfx.ViewType = {
    INVALID = 0,
    STORAGEBUFFER = 1,
    STORAGEIMAGE = 2,
    TEXTURE = 3,
    COLORATTACHMENT = 4,
    RESOLVEATTACHMENT = 5,
    DEPTHSTENCILATTACHMENT = 6,
}

---@enum gfx.ShaderStage
gfx.ShaderStage = {
    NONE = 0,
    VERTEX = 1,
    FRAGMENT = 2,
    COMPUTE = 3,
}

---@enum gfx.ShaderAttrBaseType
gfx.ShaderAttrBaseType = {
    UNDEFINED = 0,
    FLOAT = 1,
    SINT = 2,
    UINT = 3,
}

---@enum gfx.LogItem
gfx.LogItem = {
    OK = 0,
    MALLOC_FAILED = 1,
    GL_TEXTURE_FORMAT_NOT_SUPPORTED = 2,
    GL_3D_TEXTURES_NOT_SUPPORTED = 3,
    GL_ARRAY_TEXTURES_NOT_SUPPORTED = 4,
    GL_STORAGEBUFFER_GLSL_BINDING_OUT_OF_RANGE = 5,
    GL_STORAGEIMAGE_GLSL_BINDING_OUT_OF_RANGE = 6,
    GL_SHADER_COMPILATION_FAILED = 7,
    GL_SHADER_LINKING_FAILED = 8,
    GL_VERTEX_ATTRIBUTE_NOT_FOUND_IN_SHADER = 9,
    GL_UNIFORMBLOCK_NAME_NOT_FOUND_IN_SHADER = 10,
    GL_IMAGE_SAMPLER_NAME_NOT_FOUND_IN_SHADER = 11,
    GL_FRAMEBUFFER_STATUS_UNDEFINED = 12,
    GL_FRAMEBUFFER_STATUS_INCOMPLETE_ATTACHMENT = 13,
    GL_FRAMEBUFFER_STATUS_INCOMPLETE_MISSING_ATTACHMENT = 14,
    GL_FRAMEBUFFER_STATUS_UNSUPPORTED = 15,
    GL_FRAMEBUFFER_STATUS_INCOMPLETE_MULTISAMPLE = 16,
    GL_FRAMEBUFFER_STATUS_UNKNOWN = 17,
    D3D11_FEATURE_LEVEL_0_DETECTED = 18,
    D3D11_CREATE_BUFFER_FAILED = 19,
    D3D11_CREATE_BUFFER_SRV_FAILED = 20,
    D3D11_CREATE_BUFFER_UAV_FAILED = 21,
    D3D11_CREATE_DEPTH_TEXTURE_UNSUPPORTED_PIXEL_FORMAT = 22,
    D3D11_CREATE_DEPTH_TEXTURE_FAILED = 23,
    D3D11_CREATE_2D_TEXTURE_UNSUPPORTED_PIXEL_FORMAT = 24,
    D3D11_CREATE_2D_TEXTURE_FAILED = 25,
    D3D11_CREATE_2D_SRV_FAILED = 26,
    D3D11_CREATE_3D_TEXTURE_UNSUPPORTED_PIXEL_FORMAT = 27,
    D3D11_CREATE_3D_TEXTURE_FAILED = 28,
    D3D11_CREATE_3D_SRV_FAILED = 29,
    D3D11_CREATE_MSAA_TEXTURE_FAILED = 30,
    D3D11_CREATE_SAMPLER_STATE_FAILED = 31,
    D3D11_UNIFORMBLOCK_HLSL_REGISTER_B_OUT_OF_RANGE = 32,
    D3D11_STORAGEBUFFER_HLSL_REGISTER_T_OUT_OF_RANGE = 33,
    D3D11_STORAGEBUFFER_HLSL_REGISTER_U_OUT_OF_RANGE = 34,
    D3D11_IMAGE_HLSL_REGISTER_T_OUT_OF_RANGE = 35,
    D3D11_STORAGEIMAGE_HLSL_REGISTER_U_OUT_OF_RANGE = 36,
    D3D11_SAMPLER_HLSL_REGISTER_S_OUT_OF_RANGE = 37,
    D3D11_LOAD_D3DCOMPILER_47_DLL_FAILED = 38,
    D3D11_SHADER_COMPILATION_FAILED = 39,
    D3D11_SHADER_COMPILATION_OUTPUT = 40,
    D3D11_CREATE_CONSTANT_BUFFER_FAILED = 41,
    D3D11_CREATE_INPUT_LAYOUT_FAILED = 42,
    D3D11_CREATE_RASTERIZER_STATE_FAILED = 43,
    D3D11_CREATE_DEPTH_STENCIL_STATE_FAILED = 44,
    D3D11_CREATE_BLEND_STATE_FAILED = 45,
    D3D11_CREATE_RTV_FAILED = 46,
    D3D11_CREATE_DSV_FAILED = 47,
    D3D11_CREATE_UAV_FAILED = 48,
    D3D11_MAP_FOR_UPDATE_BUFFER_FAILED = 49,
    D3D11_MAP_FOR_APPEND_BUFFER_FAILED = 50,
    D3D11_MAP_FOR_UPDATE_IMAGE_FAILED = 51,
    METAL_CREATE_BUFFER_FAILED = 52,
    METAL_TEXTURE_FORMAT_NOT_SUPPORTED = 53,
    METAL_CREATE_TEXTURE_FAILED = 54,
    METAL_CREATE_SAMPLER_FAILED = 55,
    METAL_SHADER_COMPILATION_FAILED = 56,
    METAL_SHADER_CREATION_FAILED = 57,
    METAL_SHADER_COMPILATION_OUTPUT = 58,
    METAL_SHADER_ENTRY_NOT_FOUND = 59,
    METAL_UNIFORMBLOCK_MSL_BUFFER_SLOT_OUT_OF_RANGE = 60,
    METAL_STORAGEBUFFER_MSL_BUFFER_SLOT_OUT_OF_RANGE = 61,
    METAL_STORAGEIMAGE_MSL_TEXTURE_SLOT_OUT_OF_RANGE = 62,
    METAL_IMAGE_MSL_TEXTURE_SLOT_OUT_OF_RANGE = 63,
    METAL_SAMPLER_MSL_SAMPLER_SLOT_OUT_OF_RANGE = 64,
    METAL_CREATE_CPS_FAILED = 65,
    METAL_CREATE_CPS_OUTPUT = 66,
    METAL_CREATE_RPS_FAILED = 67,
    METAL_CREATE_RPS_OUTPUT = 68,
    METAL_CREATE_DSS_FAILED = 69,
    WGPU_BINDGROUPS_POOL_EXHAUSTED = 70,
    WGPU_BINDGROUPSCACHE_SIZE_GREATER_ONE = 71,
    WGPU_BINDGROUPSCACHE_SIZE_POW2 = 72,
    WGPU_CREATEBINDGROUP_FAILED = 73,
    WGPU_CREATE_BUFFER_FAILED = 74,
    WGPU_CREATE_TEXTURE_FAILED = 75,
    WGPU_CREATE_TEXTURE_VIEW_FAILED = 76,
    WGPU_CREATE_SAMPLER_FAILED = 77,
    WGPU_CREATE_SHADER_MODULE_FAILED = 78,
    WGPU_SHADER_CREATE_BINDGROUP_LAYOUT_FAILED = 79,
    WGPU_UNIFORMBLOCK_WGSL_GROUP0_BINDING_OUT_OF_RANGE = 80,
    WGPU_TEXTURE_WGSL_GROUP1_BINDING_OUT_OF_RANGE = 81,
    WGPU_STORAGEBUFFER_WGSL_GROUP1_BINDING_OUT_OF_RANGE = 82,
    WGPU_STORAGEIMAGE_WGSL_GROUP1_BINDING_OUT_OF_RANGE = 83,
    WGPU_SAMPLER_WGSL_GROUP1_BINDING_OUT_OF_RANGE = 84,
    WGPU_CREATE_PIPELINE_LAYOUT_FAILED = 85,
    WGPU_CREATE_RENDER_PIPELINE_FAILED = 86,
    WGPU_CREATE_COMPUTE_PIPELINE_FAILED = 87,
    VULKAN_REQUIRED_EXTENSION_FUNCTION_MISSING = 88,
    VULKAN_ALLOC_DEVICE_MEMORY_NO_SUITABLE_MEMORY_TYPE = 89,
    VULKAN_ALLOCATE_MEMORY_FAILED = 90,
    VULKAN_ALLOC_BUFFER_DEVICE_MEMORY_FAILED = 91,
    VULKAN_ALLOC_IMAGE_DEVICE_MEMORY_FAILED = 92,
    VULKAN_DELETE_QUEUE_EXHAUSTED = 93,
    VULKAN_STAGING_CREATE_BUFFER_FAILED = 94,
    VULKAN_STAGING_ALLOCATE_MEMORY_FAILED = 95,
    VULKAN_STAGING_BIND_BUFFER_MEMORY_FAILED = 96,
    VULKAN_STAGING_STREAM_BUFFER_OVERFLOW = 97,
    VULKAN_CREATE_SHARED_BUFFER_FAILED = 98,
    VULKAN_ALLOCATE_SHARED_BUFFER_MEMORY_FAILED = 99,
    VULKAN_BIND_SHARED_BUFFER_MEMORY_FAILED = 100,
    VULKAN_MAP_SHARED_BUFFER_MEMORY_FAILED = 101,
    VULKAN_CREATE_BUFFER_FAILED = 102,
    VULKAN_BIND_BUFFER_MEMORY_FAILED = 103,
    VULKAN_CREATE_IMAGE_FAILED = 104,
    VULKAN_BIND_IMAGE_MEMORY_FAILED = 105,
    VULKAN_CREATE_SHADER_MODULE_FAILED = 106,
    VULKAN_UNIFORMBLOCK_SPIRV_SET0_BINDING_OUT_OF_RANGE = 107,
    VULKAN_TEXTURE_SPIRV_SET1_BINDING_OUT_OF_RANGE = 108,
    VULKAN_STORAGEBUFFER_SPIRV_SET1_BINDING_OUT_OF_RANGE = 109,
    VULKAN_STORAGEIMAGE_SPIRV_SET1_BINDING_OUT_OF_RANGE = 110,
    VULKAN_SAMPLER_SPIRV_SET1_BINDING_OUT_OF_RANGE = 111,
    VULKAN_CREATE_DESCRIPTOR_SET_LAYOUT_FAILED = 112,
    VULKAN_CREATE_PIPELINE_LAYOUT_FAILED = 113,
    VULKAN_CREATE_GRAPHICS_PIPELINE_FAILED = 114,
    VULKAN_CREATE_COMPUTE_PIPELINE_FAILED = 115,
    VULKAN_CREATE_IMAGE_VIEW_FAILED = 116,
    VULKAN_VIEW_MAX_DESCRIPTOR_SIZE = 117,
    VULKAN_CREATE_SAMPLER_FAILED = 118,
    VULKAN_SAMPLER_MAX_DESCRIPTOR_SIZE = 119,
    VULKAN_WAIT_FOR_FENCE_FAILED = 120,
    VULKAN_UNIFORM_BUFFER_OVERFLOW = 121,
    VULKAN_DESCRIPTOR_BUFFER_OVERFLOW = 122,
    IDENTICAL_COMMIT_LISTENER = 123,
    COMMIT_LISTENER_ARRAY_FULL = 124,
    TRACE_HOOKS_NOT_ENABLED = 125,
    DEALLOC_BUFFER_INVALID_STATE = 126,
    DEALLOC_IMAGE_INVALID_STATE = 127,
    DEALLOC_SAMPLER_INVALID_STATE = 128,
    DEALLOC_SHADER_INVALID_STATE = 129,
    DEALLOC_PIPELINE_INVALID_STATE = 130,
    DEALLOC_VIEW_INVALID_STATE = 131,
    INIT_BUFFER_INVALID_STATE = 132,
    INIT_IMAGE_INVALID_STATE = 133,
    INIT_SAMPLER_INVALID_STATE = 134,
    INIT_SHADER_INVALID_STATE = 135,
    INIT_PIPELINE_INVALID_STATE = 136,
    INIT_VIEW_INVALID_STATE = 137,
    UNINIT_BUFFER_INVALID_STATE = 138,
    UNINIT_IMAGE_INVALID_STATE = 139,
    UNINIT_SAMPLER_INVALID_STATE = 140,
    UNINIT_SHADER_INVALID_STATE = 141,
    UNINIT_PIPELINE_INVALID_STATE = 142,
    UNINIT_VIEW_INVALID_STATE = 143,
    FAIL_BUFFER_INVALID_STATE = 144,
    FAIL_IMAGE_INVALID_STATE = 145,
    FAIL_SAMPLER_INVALID_STATE = 146,
    FAIL_SHADER_INVALID_STATE = 147,
    FAIL_PIPELINE_INVALID_STATE = 148,
    FAIL_VIEW_INVALID_STATE = 149,
    BUFFER_POOL_EXHAUSTED = 150,
    IMAGE_POOL_EXHAUSTED = 151,
    SAMPLER_POOL_EXHAUSTED = 152,
    SHADER_POOL_EXHAUSTED = 153,
    PIPELINE_POOL_EXHAUSTED = 154,
    VIEW_POOL_EXHAUSTED = 155,
    BEGINPASS_TOO_MANY_COLOR_ATTACHMENTS = 156,
    BEGINPASS_TOO_MANY_RESOLVE_ATTACHMENTS = 157,
    BEGINPASS_ATTACHMENTS_ALIVE = 158,
    DRAW_WITHOUT_BINDINGS = 159,
    SHADERDESC_TOO_MANY_VERTEXSTAGE_TEXTURES = 160,
    SHADERDESC_TOO_MANY_FRAGMENTSTAGE_TEXTURES = 161,
    SHADERDESC_TOO_MANY_COMPUTESTAGE_TEXTURES = 162,
    SHADERDESC_TOO_MANY_VERTEXSTAGE_STORAGEBUFFERS = 163,
    SHADERDESC_TOO_MANY_FRAGMENTSTAGE_STORAGEBUFFERS = 164,
    SHADERDESC_TOO_MANY_COMPUTESTAGE_STORAGEBUFFERS = 165,
    SHADERDESC_TOO_MANY_VERTEXSTAGE_STORAGEIMAGES = 166,
    SHADERDESC_TOO_MANY_FRAGMENTSTAGE_STORAGEIMAGES = 167,
    SHADERDESC_TOO_MANY_COMPUTESTAGE_STORAGEIMAGES = 168,
    SHADERDESC_TOO_MANY_VERTEXSTAGE_TEXTURESAMPLERPAIRS = 169,
    SHADERDESC_TOO_MANY_FRAGMENTSTAGE_TEXTURESAMPLERPAIRS = 170,
    SHADERDESC_TOO_MANY_COMPUTESTAGE_TEXTURESAMPLERPAIRS = 171,
    VALIDATE_BUFFERDESC_CANARY = 172,
    VALIDATE_BUFFERDESC_IMMUTABLE_DYNAMIC_STREAM = 173,
    VALIDATE_BUFFERDESC_SEPARATE_BUFFER_TYPES = 174,
    VALIDATE_BUFFERDESC_EXPECT_NONZERO_SIZE = 175,
    VALIDATE_BUFFERDESC_EXPECT_MATCHING_DATA_SIZE = 176,
    VALIDATE_BUFFERDESC_EXPECT_ZERO_DATA_SIZE = 177,
    VALIDATE_BUFFERDESC_EXPECT_NO_DATA = 178,
    VALIDATE_BUFFERDESC_EXPECT_DATA = 179,
    VALIDATE_BUFFERDESC_STORAGEBUFFER_SUPPORTED = 180,
    VALIDATE_BUFFERDESC_STORAGEBUFFER_SIZE_MULTIPLE_4 = 181,
    VALIDATE_IMAGEDATA_NODATA = 182,
    VALIDATE_IMAGEDATA_DATA_SIZE = 183,
    VALIDATE_IMAGEDESC_CANARY = 184,
    VALIDATE_IMAGEDESC_IMMUTABLE_DYNAMIC_STREAM = 185,
    VALIDATE_IMAGEDESC_IMAGETYPE_2D_NUMSLICES = 186,
    VALIDATE_IMAGEDESC_IMAGETYPE_CUBE_NUMSLICES = 187,
    VALIDATE_IMAGEDESC_IMAGETYPE_ARRAY_NUMSLICES = 188,
    VALIDATE_IMAGEDESC_IMAGETYPE_3D_NUMSLICES = 189,
    VALIDATE_IMAGEDESC_NUMSLICES = 190,
    VALIDATE_IMAGEDESC_WIDTH = 191,
    VALIDATE_IMAGEDESC_HEIGHT = 192,
    VALIDATE_IMAGEDESC_NONRT_PIXELFORMAT = 193,
    VALIDATE_IMAGEDESC_MSAA_BUT_NO_ATTACHMENT = 194,
    VALIDATE_IMAGEDESC_DEPTH_3D_IMAGE = 195,
    VALIDATE_IMAGEDESC_ATTACHMENT_EXPECT_IMMUTABLE = 196,
    VALIDATE_IMAGEDESC_ATTACHMENT_EXPECT_NO_DATA = 197,
    VALIDATE_IMAGEDESC_ATTACHMENT_PIXELFORMAT = 198,
    VALIDATE_IMAGEDESC_ATTACHMENT_RESOLVE_EXPECT_NO_MSAA = 199,
    VALIDATE_IMAGEDESC_ATTACHMENT_NO_MSAA_SUPPORT = 200,
    VALIDATE_IMAGEDESC_ATTACHMENT_MSAA_NUM_MIPMAPS = 201,
    VALIDATE_IMAGEDESC_ATTACHMENT_MSAA_3D_IMAGE = 202,
    VALIDATE_IMAGEDESC_ATTACHMENT_MSAA_CUBE_IMAGE = 203,
    VALIDATE_IMAGEDESC_ATTACHMENT_MSAA_ARRAY_IMAGE = 204,
    VALIDATE_IMAGEDESC_STORAGEIMAGE_PIXELFORMAT = 205,
    VALIDATE_IMAGEDESC_STORAGEIMAGE_EXPECT_NO_MSAA = 206,
    VALIDATE_IMAGEDESC_INJECTED_NO_DATA = 207,
    VALIDATE_IMAGEDESC_DYNAMIC_NO_DATA = 208,
    VALIDATE_IMAGEDESC_COMPRESSED_IMMUTABLE = 209,
    VALIDATE_SAMPLERDESC_CANARY = 210,
    VALIDATE_SAMPLERDESC_ANISTROPIC_REQUIRES_LINEAR_FILTERING = 211,
    VALIDATE_SHADERDESC_CANARY = 212,
    VALIDATE_SHADERDESC_VERTEX_SOURCE = 213,
    VALIDATE_SHADERDESC_FRAGMENT_SOURCE = 214,
    VALIDATE_SHADERDESC_COMPUTE_SOURCE = 215,
    VALIDATE_SHADERDESC_VERTEX_SOURCE_OR_BYTECODE = 216,
    VALIDATE_SHADERDESC_FRAGMENT_SOURCE_OR_BYTECODE = 217,
    VALIDATE_SHADERDESC_COMPUTE_SOURCE_OR_BYTECODE = 218,
    VALIDATE_SHADERDESC_INVALID_SHADER_COMBO = 219,
    VALIDATE_SHADERDESC_NO_BYTECODE_SIZE = 220,
    VALIDATE_SHADERDESC_METAL_THREADS_PER_THREADGROUP_INITIALIZED = 221,
    VALIDATE_SHADERDESC_METAL_THREADS_PER_THREADGROUP_MULTIPLE_32 = 222,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_NO_CONT_MEMBERS = 223,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_SIZE_IS_ZERO = 224,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_METAL_BUFFER_SLOT_COLLISION = 225,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_HLSL_REGISTER_B_COLLISION = 226,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_WGSL_GROUP0_BINDING_COLLISION = 227,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_SPIRV_SET0_BINDING_COLLISION = 228,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_NO_MEMBERS = 229,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_UNIFORM_GLSL_NAME = 230,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_SIZE_MISMATCH = 231,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_ARRAY_COUNT = 232,
    VALIDATE_SHADERDESC_UNIFORMBLOCK_STD140_ARRAY_TYPE = 233,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_METAL_BUFFER_SLOT_COLLISION = 234,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_HLSL_REGISTER_T_COLLISION = 235,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_HLSL_REGISTER_U_COLLISION = 236,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_GLSL_BINDING_COLLISION = 237,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_WGSL_GROUP1_BINDING_COLLISION = 238,
    VALIDATE_SHADERDESC_VIEW_STORAGEBUFFER_SPIRV_SET1_BINDING_COLLISION = 239,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_EXPECT_COMPUTE_STAGE = 240,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_METAL_TEXTURE_SLOT_COLLISION = 241,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_HLSL_REGISTER_U_COLLISION = 242,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_GLSL_BINDING_COLLISION = 243,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_WGSL_GROUP1_BINDING_COLLISION = 244,
    VALIDATE_SHADERDESC_VIEW_STORAGEIMAGE_SPIRV_SET1_BINDING_COLLISION = 245,
    VALIDATE_SHADERDESC_VIEW_TEXTURE_METAL_TEXTURE_SLOT_COLLISION = 246,
    VALIDATE_SHADERDESC_VIEW_TEXTURE_HLSL_REGISTER_T_COLLISION = 247,
    VALIDATE_SHADERDESC_VIEW_TEXTURE_WGSL_GROUP1_BINDING_COLLISION = 248,
    VALIDATE_SHADERDESC_VIEW_TEXTURE_SPIRV_SET1_BINDING_COLLISION = 249,
    VALIDATE_SHADERDESC_SAMPLER_METAL_SAMPLER_SLOT_COLLISION = 250,
    VALIDATE_SHADERDESC_SAMPLER_HLSL_REGISTER_S_COLLISION = 251,
    VALIDATE_SHADERDESC_SAMPLER_WGSL_GROUP1_BINDING_COLLISION = 252,
    VALIDATE_SHADERDESC_SAMPLER_SPIRV_SET1_BINDING_COLLISION = 253,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_VIEW_SLOT_OUT_OF_RANGE = 254,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_SAMPLER_SLOT_OUT_OF_RANGE = 255,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_TEXTURE_STAGE_MISMATCH = 256,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_EXPECT_TEXTURE_VIEW = 257,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_SAMPLER_STAGE_MISMATCH = 258,
    VALIDATE_SHADERDESC_TEXTURE_SAMPLER_PAIR_GLSL_NAME = 259,
    VALIDATE_SHADERDESC_NONFILTERING_SAMPLER_REQUIRED = 260,
    VALIDATE_SHADERDESC_COMPARISON_SAMPLER_REQUIRED = 261,
    VALIDATE_SHADERDESC_TEXVIEW_NOT_REFERENCED_BY_TEXTURE_SAMPLER_PAIRS = 262,
    VALIDATE_SHADERDESC_SAMPLER_NOT_REFERENCED_BY_TEXTURE_SAMPLER_PAIRS = 263,
    VALIDATE_SHADERDESC_ATTR_STRING_TOO_LONG = 264,
    VALIDATE_PIPELINEDESC_CANARY = 265,
    VALIDATE_PIPELINEDESC_SHADER = 266,
    VALIDATE_PIPELINEDESC_COMPUTE_SHADER_EXPECTED = 267,
    VALIDATE_PIPELINEDESC_NO_COMPUTE_SHADER_EXPECTED = 268,
    VALIDATE_PIPELINEDESC_NO_CONT_ATTRS = 269,
    VALIDATE_PIPELINEDESC_ATTR_BASETYPE_MISMATCH = 270,
    VALIDATE_PIPELINEDESC_LAYOUT_STRIDE4 = 271,
    VALIDATE_PIPELINEDESC_ATTR_SEMANTICS = 272,
    VALIDATE_PIPELINEDESC_SHADER_READONLY_STORAGEBUFFERS = 273,
    VALIDATE_PIPELINEDESC_BLENDOP_MINMAX_REQUIRES_BLENDFACTOR_ONE = 274,
    VALIDATE_VIEWDESC_CANARY = 275,
    VALIDATE_VIEWDESC_UNIQUE_VIEWTYPE = 276,
    VALIDATE_VIEWDESC_ANY_VIEWTYPE = 277,
    VALIDATE_VIEWDESC_RESOURCE_ALIVE = 278,
    VALIDATE_VIEWDESC_RESOURCE_FAILED = 279,
    VALIDATE_VIEWDESC_STORAGEBUFFER_OFFSET_VS_BUFFER_SIZE = 280,
    VALIDATE_VIEWDESC_STORAGEBUFFER_OFFSET_MULTIPLE_256 = 281,
    VALIDATE_VIEWDESC_STORAGEBUFFER_USAGE = 282,
    VALIDATE_VIEWDESC_STORAGEIMAGE_USAGE = 283,
    VALIDATE_VIEWDESC_COLORATTACHMENT_USAGE = 284,
    VALIDATE_VIEWDESC_RESOLVEATTACHMENT_USAGE = 285,
    VALIDATE_VIEWDESC_DEPTHSTENCILATTACHMENT_USAGE = 286,
    VALIDATE_VIEWDESC_IMAGE_MIPLEVEL = 287,
    VALIDATE_VIEWDESC_IMAGE_2D_SLICE = 288,
    VALIDATE_VIEWDESC_IMAGE_CUBEMAP_SLICE = 289,
    VALIDATE_VIEWDESC_IMAGE_ARRAY_SLICE = 290,
    VALIDATE_VIEWDESC_IMAGE_3D_SLICE = 291,
    VALIDATE_VIEWDESC_TEXTURE_EXPECT_NO_MSAA = 292,
    VALIDATE_VIEWDESC_TEXTURE_MIPLEVELS = 293,
    VALIDATE_VIEWDESC_TEXTURE_2D_SLICES = 294,
    VALIDATE_VIEWDESC_TEXTURE_CUBEMAP_SLICES = 295,
    VALIDATE_VIEWDESC_TEXTURE_ARRAY_SLICES = 296,
    VALIDATE_VIEWDESC_TEXTURE_3D_SLICES = 297,
    VALIDATE_VIEWDESC_STORAGEIMAGE_PIXELFORMAT = 298,
    VALIDATE_VIEWDESC_COLORATTACHMENT_PIXELFORMAT = 299,
    VALIDATE_VIEWDESC_DEPTHSTENCILATTACHMENT_PIXELFORMAT = 300,
    VALIDATE_VIEWDESC_RESOLVEATTACHMENT_SAMPLECOUNT = 301,
    VALIDATE_BEGINPASS_CANARY = 302,
    VALIDATE_BEGINPASS_COMPUTEPASS_EXPECT_NO_ATTACHMENTS = 303,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_WIDTH = 304,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_WIDTH_NOTSET = 305,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_HEIGHT = 306,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_HEIGHT_NOTSET = 307,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_SAMPLECOUNT = 308,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_SAMPLECOUNT_NOTSET = 309,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_COLORFORMAT = 310,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_COLORFORMAT_NOTSET = 311,
    VALIDATE_BEGINPASS_SWAPCHAIN_EXPECT_DEPTHFORMAT_NOTSET = 312,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_CURRENTDRAWABLE = 313,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_CURRENTDRAWABLE_NOTSET = 314,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_DEPTHSTENCILTEXTURE = 315,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_DEPTHSTENCILTEXTURE_NOTSET = 316,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_MSAACOLORTEXTURE = 317,
    VALIDATE_BEGINPASS_SWAPCHAIN_METAL_EXPECT_MSAACOLORTEXTURE_NOTSET = 318,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_RENDERVIEW = 319,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_RENDERVIEW_NOTSET = 320,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_RESOLVEVIEW = 321,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_RESOLVEVIEW_NOTSET = 322,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_DEPTHSTENCILVIEW = 323,
    VALIDATE_BEGINPASS_SWAPCHAIN_D3D11_EXPECT_DEPTHSTENCILVIEW_NOTSET = 324,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_RENDERVIEW = 325,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_RENDERVIEW_NOTSET = 326,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_RESOLVEVIEW = 327,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_RESOLVEVIEW_NOTSET = 328,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_DEPTHSTENCILVIEW = 329,
    VALIDATE_BEGINPASS_SWAPCHAIN_WGPU_EXPECT_DEPTHSTENCILVIEW_NOTSET = 330,
    VALIDATE_BEGINPASS_SWAPCHAIN_GL_EXPECT_FRAMEBUFFER_NOTSET = 331,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEWS_CONTINUOUS = 332,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_ALIVE = 333,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_VALID = 334,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_TYPE = 335,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_IMAGE_ALIVE = 336,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_IMAGE_VALID = 337,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_SIZES = 338,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_SAMPLECOUNT = 339,
    VALIDATE_BEGINPASS_COLORATTACHMENTVIEW_SAMPLECOUNTS_EQUAL = 340,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_NO_COLORATTACHMENTVIEW = 341,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_ALIVE = 342,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_VALID = 343,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_TYPE = 344,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_IMAGE_ALIVE = 345,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_IMAGE_VALID = 346,
    VALIDATE_BEGINPASS_RESOLVEATTACHMENTVIEW_SIZES = 347,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEWS_CONTINUOUS = 348,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_ALIVE = 349,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_VALID = 350,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_TYPE = 351,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_IMAGE_ALIVE = 352,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_IMAGE_VALID = 353,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_SIZES = 354,
    VALIDATE_BEGINPASS_DEPTHSTENCILATTACHMENTVIEW_SAMPLECOUNT = 355,
    VALIDATE_BEGINPASS_ATTACHMENTS_EXPECTED = 356,
    VALIDATE_AVP_RENDERPASS_EXPECTED = 357,
    VALIDATE_ASR_RENDERPASS_EXPECTED = 358,
    VALIDATE_APIP_PIPELINE_VALID_ID = 359,
    VALIDATE_APIP_PIPELINE_EXISTS = 360,
    VALIDATE_APIP_PIPELINE_VALID = 361,
    VALIDATE_APIP_PASS_EXPECTED = 362,
    VALIDATE_APIP_PIPELINE_SHADER_ALIVE = 363,
    VALIDATE_APIP_PIPELINE_SHADER_VALID = 364,
    VALIDATE_APIP_COMPUTEPASS_EXPECTED = 365,
    VALIDATE_APIP_RENDERPASS_EXPECTED = 366,
    VALIDATE_APIP_SWAPCHAIN_COLOR_COUNT = 367,
    VALIDATE_APIP_SWAPCHAIN_COLOR_FORMAT = 368,
    VALIDATE_APIP_SWAPCHAIN_DEPTH_FORMAT = 369,
    VALIDATE_APIP_SWAPCHAIN_SAMPLE_COUNT = 370,
    VALIDATE_APIP_ATTACHMENTS_ALIVE = 371,
    VALIDATE_APIP_COLORATTACHMENTS_COUNT = 372,
    VALIDATE_APIP_COLORATTACHMENTS_VIEW_VALID = 373,
    VALIDATE_APIP_COLORATTACHMENTS_IMAGE_VALID = 374,
    VALIDATE_APIP_COLORATTACHMENTS_FORMAT = 375,
    VALIDATE_APIP_DEPTHSTENCILATTACHMENT_VIEW_VALID = 376,
    VALIDATE_APIP_DEPTHSTENCILATTACHMENT_IMAGE_VALID = 377,
    VALIDATE_APIP_DEPTHSTENCILATTACHMENT_FORMAT = 378,
    VALIDATE_APIP_ATTACHMENT_SAMPLE_COUNT = 379,
    VALIDATE_ABND_PASS_EXPECTED = 380,
    VALIDATE_ABND_EMPTY_BINDINGS = 381,
    VALIDATE_ABND_NO_PIPELINE = 382,
    VALIDATE_ABND_PIPELINE_ALIVE = 383,
    VALIDATE_ABND_PIPELINE_VALID = 384,
    VALIDATE_ABND_PIPELINE_SHADER_ALIVE = 385,
    VALIDATE_ABND_PIPELINE_SHADER_VALID = 386,
    VALIDATE_ABND_COMPUTE_EXPECTED_NO_VBUFS = 387,
    VALIDATE_ABND_COMPUTE_EXPECTED_NO_IBUF = 388,
    VALIDATE_ABND_EXPECTED_VBUF = 389,
    VALIDATE_ABND_VBUF_ALIVE = 390,
    VALIDATE_ABND_VBUF_USAGE = 391,
    VALIDATE_ABND_VBUF_OVERFLOW = 392,
    VALIDATE_ABND_EXPECTED_NO_IBUF = 393,
    VALIDATE_ABND_EXPECTED_IBUF = 394,
    VALIDATE_ABND_IBUF_ALIVE = 395,
    VALIDATE_ABND_IBUF_USAGE = 396,
    VALIDATE_ABND_IBUF_OVERFLOW = 397,
    VALIDATE_ABND_EXPECTED_VIEW_BINDING = 398,
    VALIDATE_ABND_VIEW_ALIVE = 399,
    VALIDATE_ABND_EXPECT_TEXVIEW = 400,
    VALIDATE_ABND_EXPECT_SBVIEW = 401,
    VALIDATE_ABND_EXPECT_SIMGVIEW = 402,
    VALIDATE_ABND_TEXVIEW_IMAGETYPE_MISMATCH = 403,
    VALIDATE_ABND_TEXVIEW_EXPECTED_MULTISAMPLED_IMAGE = 404,
    VALIDATE_ABND_TEXVIEW_EXPECTED_NON_MULTISAMPLED_IMAGE = 405,
    VALIDATE_ABND_TEXVIEW_EXPECTED_FILTERABLE_IMAGE = 406,
    VALIDATE_ABND_TEXVIEW_EXPECTED_DEPTH_IMAGE = 407,
    VALIDATE_ABND_SBVIEW_READWRITE_IMMUTABLE = 408,
    VALIDATE_ABND_SIMGVIEW_COMPUTE_PASS_EXPECTED = 409,
    VALIDATE_ABND_SIMGVIEW_IMAGETYPE_MISMATCH = 410,
    VALIDATE_ABND_SIMGVIEW_ACCESSFORMAT = 411,
    VALIDATE_ABND_EXPECTED_SAMPLER_BINDING = 412,
    VALIDATE_ABND_UNEXPECTED_SAMPLER_COMPARE_NEVER = 413,
    VALIDATE_ABND_EXPECTED_SAMPLER_COMPARE_NEVER = 414,
    VALIDATE_ABND_EXPECTED_NONFILTERING_SAMPLER = 415,
    VALIDATE_ABND_SAMPLER_ALIVE = 416,
    VALIDATE_ABND_SAMPLER_VALID = 417,
    VALIDATE_ABND_TEXTURE_BINDING_VS_DEPTHSTENCIL_ATTACHMENT = 418,
    VALIDATE_ABND_TEXTURE_BINDING_VS_COLOR_ATTACHMENT = 419,
    VALIDATE_ABND_TEXTURE_BINDING_VS_RESOLVE_ATTACHMENT = 420,
    VALIDATE_ABND_TEXTURE_VS_STORAGEIMAGE_BINDING = 421,
    VALIDATE_AU_PASS_EXPECTED = 422,
    VALIDATE_AU_NO_PIPELINE = 423,
    VALIDATE_AU_PIPELINE_ALIVE = 424,
    VALIDATE_AU_PIPELINE_VALID = 425,
    VALIDATE_AU_PIPELINE_SHADER_ALIVE = 426,
    VALIDATE_AU_PIPELINE_SHADER_VALID = 427,
    VALIDATE_AU_NO_UNIFORMBLOCK_AT_SLOT = 428,
    VALIDATE_AU_SIZE = 429,
    VALIDATE_DRAW_RENDERPASS_EXPECTED = 430,
    VALIDATE_DRAW_BASEELEMENT_GE_ZERO = 431,
    VALIDATE_DRAW_NUMELEMENTS_GE_ZERO = 432,
    VALIDATE_DRAW_NUMINSTANCES_GE_ZERO = 433,
    VALIDATE_DRAW_EX_RENDERPASS_EXPECTED = 434,
    VALIDATE_DRAW_EX_BASEELEMENT_GE_ZERO = 435,
    VALIDATE_DRAW_EX_NUMELEMENTS_GE_ZERO = 436,
    VALIDATE_DRAW_EX_NUMINSTANCES_GE_ZERO = 437,
    VALIDATE_DRAW_EX_BASEINSTANCE_GE_ZERO = 438,
    VALIDATE_DRAW_EX_BASEVERTEX_VS_INDEXED = 439,
    VALIDATE_DRAW_EX_BASEINSTANCE_VS_INSTANCED = 440,
    VALIDATE_DRAW_EX_BASEVERTEX_NOT_SUPPORTED = 441,
    VALIDATE_DRAW_EX_BASEINSTANCE_NOT_SUPPORTED = 442,
    VALIDATE_DRAW_REQUIRED_BINDINGS_OR_UNIFORMS_MISSING = 443,
    VALIDATE_DISPATCH_COMPUTEPASS_EXPECTED = 444,
    VALIDATE_DISPATCH_NUMGROUPSX = 445,
    VALIDATE_DISPATCH_NUMGROUPSY = 446,
    VALIDATE_DISPATCH_NUMGROUPSZ = 447,
    VALIDATE_DISPATCH_REQUIRED_BINDINGS_OR_UNIFORMS_MISSING = 448,
    VALIDATE_UPDATEBUF_USAGE = 449,
    VALIDATE_UPDATEBUF_SIZE = 450,
    VALIDATE_UPDATEBUF_ONCE = 451,
    VALIDATE_UPDATEBUF_APPEND = 452,
    VALIDATE_APPENDBUF_USAGE = 453,
    VALIDATE_APPENDBUF_SIZE = 454,
    VALIDATE_APPENDBUF_UPDATE = 455,
    VALIDATE_UPDIMG_USAGE = 456,
    VALIDATE_UPDIMG_ONCE = 457,
    VALIDATION_FAILED = 458,
}

---@class gfx.Buffer
---@field id? integer

---@class gfx.Image
---@field id? integer

---@class gfx.Sampler
---@field id? integer

---@class gfx.Shader
---@field id? integer

---@class gfx.Pipeline
---@field id? integer

---@class gfx.View
---@field id? integer

---@class gfx.Range
---@field ptr? lightuserdata?
---@field size? integer

---@class gfx.Color
---@field r? number
---@field g? number
---@field b? number
---@field a? number

---@class gfx.PixelformatInfo
---@field sample? boolean
---@field filter? boolean
---@field render? boolean
---@field blend? boolean
---@field msaa? boolean
---@field depth? boolean
---@field compressed? boolean
---@field read? boolean
---@field write? boolean
---@field bytes_per_pixel? integer

---@class gfx.Features
---@field origin_top_left? boolean
---@field image_clamp_to_border? boolean
---@field mrt_independent_blend_state? boolean
---@field mrt_independent_write_mask? boolean
---@field compute? boolean
---@field msaa_texture_bindings? boolean
---@field separate_buffer_types? boolean
---@field draw_base_vertex? boolean
---@field draw_base_instance? boolean
---@field gl_texture_views? boolean

---@class gfx.Limits
---@field max_image_size_2d? integer
---@field max_image_size_cube? integer
---@field max_image_size_3d? integer
---@field max_image_size_array? integer
---@field max_image_array_layers? integer
---@field max_vertex_attrs? integer
---@field max_color_attachments? integer
---@field max_texture_bindings_per_stage? integer
---@field max_storage_buffer_bindings_per_stage? integer
---@field max_storage_image_bindings_per_stage? integer
---@field gl_max_vertex_uniform_components? integer
---@field gl_max_combined_texture_image_units? integer
---@field d3d11_max_unordered_access_views? integer
---@field vk_min_uniform_buffer_offset_alignment? integer

---@class gfx.ColorAttachmentAction
---@field load_action? gfx.LoadAction
---@field store_action? gfx.StoreAction
---@field clear_value? gfx.Color

---@class gfx.DepthAttachmentAction
---@field load_action? gfx.LoadAction
---@field store_action? gfx.StoreAction
---@field clear_value? number

---@class gfx.StencilAttachmentAction
---@field load_action? gfx.LoadAction
---@field store_action? gfx.StoreAction
---@field clear_value? integer

---@class gfx.PassAction
---@field colors? gfx.ColorAttachmentAction[]
---@field depth? gfx.DepthAttachmentAction
---@field stencil? gfx.StencilAttachmentAction

---@class gfx.MetalSwapchain
---@field current_drawable? lightuserdata?
---@field depth_stencil_texture? lightuserdata?
---@field msaa_color_texture? lightuserdata?

---@class gfx.D3d11Swapchain
---@field render_view? lightuserdata?
---@field resolve_view? lightuserdata?
---@field depth_stencil_view? lightuserdata?

---@class gfx.WgpuSwapchain
---@field render_view? lightuserdata?
---@field resolve_view? lightuserdata?
---@field depth_stencil_view? lightuserdata?

---@class gfx.VulkanSwapchain
---@field render_image? lightuserdata?
---@field render_view? lightuserdata?
---@field resolve_image? lightuserdata?
---@field resolve_view? lightuserdata?
---@field depth_stencil_image? lightuserdata?
---@field depth_stencil_view? lightuserdata?
---@field render_finished_semaphore? lightuserdata?
---@field present_complete_semaphore? lightuserdata?

---@class gfx.GlSwapchain
---@field framebuffer? integer

---@class gfx.Swapchain
---@field width? integer
---@field height? integer
---@field sample_count? integer
---@field color_format? gfx.PixelFormat
---@field depth_format? gfx.PixelFormat
---@field metal? gfx.MetalSwapchain
---@field d3d11? gfx.D3d11Swapchain
---@field wgpu? gfx.WgpuSwapchain
---@field vulkan? gfx.VulkanSwapchain
---@field gl? gfx.GlSwapchain

---@class gfx.Attachments
---@field colors? gfx.View[]
---@field resolves? gfx.View[]
---@field depth_stencil? gfx.View

---@class gfx.Pass
---@field _start_canary? integer
---@field compute? boolean
---@field action? gfx.PassAction
---@field attachments? gfx.Attachments
---@field swapchain? gfx.Swapchain
---@field label? string
---@field _end_canary? integer

---@class gfx.Bindings
---@field _start_canary? integer
---@field vertex_buffers? gfx.Buffer[]
---@field vertex_buffer_offsets? integer[]
---@field index_buffer? gfx.Buffer
---@field index_buffer_offset? integer
---@field views? gfx.View[]
---@field samplers? gfx.Sampler[]
---@field _end_canary? integer

---@class gfx.BufferUsage
---@field vertex_buffer? boolean
---@field index_buffer? boolean
---@field storage_buffer? boolean
---@field immutable? boolean
---@field dynamic_update? boolean
---@field stream_update? boolean

---@class gfx.BufferDesc
---@field _start_canary? integer
---@field size? integer
---@field usage? gfx.BufferUsage
---@field data? gfx.Range|string
---@field label? string
---@field gl_buffers? integer[]
---@field mtl_buffers? lightuserdata?[]
---@field d3d11_buffer? lightuserdata?
---@field wgpu_buffer? lightuserdata?
---@field _end_canary? integer

---@class gfx.ImageUsage
---@field storage_image? boolean
---@field color_attachment? boolean
---@field resolve_attachment? boolean
---@field depth_stencil_attachment? boolean
---@field immutable? boolean
---@field dynamic_update? boolean
---@field stream_update? boolean

---@class gfx.ImageData
---@field mip_levels? gfx.Range[]

---@class gfx.ImageDesc
---@field _start_canary? integer
---@field type? gfx.ImageType
---@field usage? gfx.ImageUsage
---@field width? integer
---@field height? integer
---@field num_slices? integer
---@field num_mipmaps? integer
---@field pixel_format? gfx.PixelFormat
---@field sample_count? integer
---@field data? gfx.ImageData
---@field label? string
---@field gl_textures? integer[]
---@field gl_texture_target? integer
---@field mtl_textures? lightuserdata?[]
---@field d3d11_texture? lightuserdata?
---@field wgpu_texture? lightuserdata?
---@field _end_canary? integer

---@class gfx.SamplerDesc
---@field _start_canary? integer
---@field min_filter? gfx.Filter
---@field mag_filter? gfx.Filter
---@field mipmap_filter? gfx.Filter
---@field wrap_u? gfx.Wrap
---@field wrap_v? gfx.Wrap
---@field wrap_w? gfx.Wrap
---@field min_lod? number
---@field max_lod? number
---@field border_color? gfx.BorderColor
---@field compare? gfx.CompareFunc
---@field max_anisotropy? integer
---@field label? string
---@field gl_sampler? integer
---@field mtl_sampler? lightuserdata?
---@field d3d11_sampler? lightuserdata?
---@field wgpu_sampler? lightuserdata?
---@field _end_canary? integer

---@class gfx.ShaderFunction
---@field source? string
---@field bytecode? gfx.Range|string
---@field entry? string
---@field d3d11_target? string
---@field d3d11_filepath? string

---@class gfx.ShaderVertexAttr
---@field base_type? gfx.ShaderAttrBaseType
---@field glsl_name? string
---@field hlsl_sem_name? string
---@field hlsl_sem_index? integer

---@class gfx.GlslShaderUniform
---@field type? gfx.UniformType
---@field array_count? integer
---@field glsl_name? string

---@class gfx.ShaderUniformBlock
---@field stage? gfx.ShaderStage
---@field size? integer
---@field hlsl_register_b_n? integer
---@field msl_buffer_n? integer
---@field wgsl_group0_binding_n? integer
---@field spirv_set0_binding_n? integer
---@field layout? gfx.UniformLayout
---@field glsl_uniforms? gfx.GlslShaderUniform[]

---@class gfx.ShaderTextureView
---@field stage? gfx.ShaderStage
---@field image_type? gfx.ImageType
---@field sample_type? gfx.ImageSampleType
---@field multisampled? boolean
---@field hlsl_register_t_n? integer
---@field msl_texture_n? integer
---@field wgsl_group1_binding_n? integer
---@field spirv_set1_binding_n? integer

---@class gfx.ShaderStorageBufferView
---@field stage? gfx.ShaderStage
---@field readonly? boolean
---@field hlsl_register_t_n? integer
---@field hlsl_register_u_n? integer
---@field msl_buffer_n? integer
---@field wgsl_group1_binding_n? integer
---@field spirv_set1_binding_n? integer
---@field glsl_binding_n? integer

---@class gfx.ShaderStorageImageView
---@field stage? gfx.ShaderStage
---@field image_type? gfx.ImageType
---@field access_format? gfx.PixelFormat
---@field writeonly? boolean
---@field hlsl_register_u_n? integer
---@field msl_texture_n? integer
---@field wgsl_group1_binding_n? integer
---@field spirv_set1_binding_n? integer
---@field glsl_binding_n? integer

---@class gfx.ShaderView
---@field texture? gfx.ShaderTextureView
---@field storage_buffer? gfx.ShaderStorageBufferView
---@field storage_image? gfx.ShaderStorageImageView

---@class gfx.ShaderSampler
---@field stage? gfx.ShaderStage
---@field sampler_type? gfx.SamplerType
---@field hlsl_register_s_n? integer
---@field msl_sampler_n? integer
---@field wgsl_group1_binding_n? integer
---@field spirv_set1_binding_n? integer

---@class gfx.ShaderTextureSamplerPair
---@field stage? gfx.ShaderStage
---@field view_slot? integer
---@field sampler_slot? integer
---@field glsl_name? string

---@class gfx.MtlShaderThreadsPerThreadgroup
---@field x? integer
---@field y? integer
---@field z? integer

---@class gfx.ShaderDesc
---@field _start_canary? integer
---@field vertex_func? gfx.ShaderFunction
---@field fragment_func? gfx.ShaderFunction
---@field compute_func? gfx.ShaderFunction
---@field attrs? gfx.ShaderVertexAttr[]
---@field uniform_blocks? gfx.ShaderUniformBlock[]
---@field views? gfx.ShaderView[]
---@field samplers? gfx.ShaderSampler[]
---@field texture_sampler_pairs? gfx.ShaderTextureSamplerPair[]
---@field mtl_threads_per_threadgroup? gfx.MtlShaderThreadsPerThreadgroup
---@field label? string
---@field _end_canary? integer

---@class gfx.VertexBufferLayoutState
---@field stride? integer
---@field step_func? gfx.VertexStep
---@field step_rate? integer

---@class gfx.VertexAttrState
---@field buffer_index? integer
---@field offset? integer
---@field format? gfx.VertexFormat

---@class gfx.VertexLayoutState
---@field buffers? gfx.VertexBufferLayoutState[]
---@field attrs? gfx.VertexAttrState[]

---@class gfx.StencilFaceState
---@field compare? gfx.CompareFunc
---@field fail_op? gfx.StencilOp
---@field depth_fail_op? gfx.StencilOp
---@field pass_op? gfx.StencilOp

---@class gfx.StencilState
---@field enabled? boolean
---@field front? gfx.StencilFaceState
---@field back? gfx.StencilFaceState
---@field read_mask? integer
---@field write_mask? integer
---@field ref? integer

---@class gfx.DepthState
---@field pixel_format? gfx.PixelFormat
---@field compare? gfx.CompareFunc
---@field write_enabled? boolean
---@field bias? number
---@field bias_slope_scale? number
---@field bias_clamp? number

---@class gfx.BlendState
---@field enabled? boolean
---@field src_factor_rgb? gfx.BlendFactor
---@field dst_factor_rgb? gfx.BlendFactor
---@field op_rgb? gfx.BlendOp
---@field src_factor_alpha? gfx.BlendFactor
---@field dst_factor_alpha? gfx.BlendFactor
---@field op_alpha? gfx.BlendOp

---@class gfx.ColorTargetState
---@field pixel_format? gfx.PixelFormat
---@field write_mask? gfx.ColorMask
---@field blend? gfx.BlendState

---@class gfx.PipelineDesc
---@field _start_canary? integer
---@field compute? boolean
---@field shader? gfx.Shader
---@field layout? gfx.VertexLayoutState
---@field depth? gfx.DepthState
---@field stencil? gfx.StencilState
---@field color_count? integer
---@field colors? gfx.ColorTargetState[]
---@field primitive_type? gfx.PrimitiveType
---@field index_type? gfx.IndexType
---@field cull_mode? gfx.CullMode
---@field face_winding? gfx.FaceWinding
---@field sample_count? integer
---@field blend_color? gfx.Color
---@field alpha_to_coverage_enabled? boolean
---@field label? string
---@field _end_canary? integer

---@class gfx.BufferViewDesc
---@field buffer? gfx.Buffer
---@field offset? integer

---@class gfx.ImageViewDesc
---@field image? gfx.Image
---@field mip_level? integer
---@field slice? integer

---@class gfx.TextureViewRange
---@field base? integer
---@field count? integer

---@class gfx.TextureViewDesc
---@field image? gfx.Image
---@field mip_levels? gfx.TextureViewRange
---@field slices? gfx.TextureViewRange

---@class gfx.ViewDesc
---@field _start_canary? integer
---@field texture? gfx.TextureViewDesc
---@field storage_buffer? gfx.BufferViewDesc
---@field storage_image? gfx.ImageViewDesc
---@field color_attachment? gfx.ImageViewDesc
---@field resolve_attachment? gfx.ImageViewDesc
---@field depth_stencil_attachment? gfx.ImageViewDesc
---@field label? string
---@field _end_canary? integer

---@class gfx.TraceHooks
---@field user_data? lightuserdata?
---@field reset_state_cache? any
---@field make_buffer? any
---@field make_image? any
---@field make_sampler? any
---@field make_shader? any
---@field make_pipeline? any
---@field make_view? any
---@field destroy_buffer? any
---@field destroy_image? any
---@field destroy_sampler? any
---@field destroy_shader? any
---@field destroy_pipeline? any
---@field destroy_view? any
---@field update_buffer? any
---@field update_image? any
---@field append_buffer? any
---@field begin_pass? any
---@field apply_viewport? any
---@field apply_scissor_rect? any
---@field apply_pipeline? any
---@field apply_bindings? any
---@field apply_uniforms? any
---@field draw? any
---@field draw_ex? any
---@field dispatch? any
---@field end_pass? any
---@field commit? any
---@field alloc_buffer? any
---@field alloc_image? any
---@field alloc_sampler? any
---@field alloc_shader? any
---@field alloc_pipeline? any
---@field alloc_view? any
---@field dealloc_buffer? any
---@field dealloc_image? any
---@field dealloc_sampler? any
---@field dealloc_shader? any
---@field dealloc_pipeline? any
---@field dealloc_view? any
---@field init_buffer? any
---@field init_image? any
---@field init_sampler? any
---@field init_shader? any
---@field init_pipeline? any
---@field init_view? any
---@field uninit_buffer? any
---@field uninit_image? any
---@field uninit_sampler? any
---@field uninit_shader? any
---@field uninit_pipeline? any
---@field uninit_view? any
---@field fail_buffer? any
---@field fail_image? any
---@field fail_sampler? any
---@field fail_shader? any
---@field fail_pipeline? any
---@field fail_view? any
---@field push_debug_group? any
---@field pop_debug_group? any

---@class gfx.SlotInfo
---@field state? gfx.ResourceState
---@field res_id? integer
---@field uninit_count? integer

---@class gfx.BufferInfo
---@field slot? gfx.SlotInfo
---@field update_frame_index? integer
---@field append_frame_index? integer
---@field append_pos? integer
---@field append_overflow? boolean
---@field num_slots? integer
---@field active_slot? integer

---@class gfx.ImageInfo
---@field slot? gfx.SlotInfo
---@field upd_frame_index? integer
---@field num_slots? integer
---@field active_slot? integer

---@class gfx.SamplerInfo
---@field slot? gfx.SlotInfo

---@class gfx.ShaderInfo
---@field slot? gfx.SlotInfo

---@class gfx.PipelineInfo
---@field slot? gfx.SlotInfo

---@class gfx.ViewInfo
---@field slot? gfx.SlotInfo

---@class gfx.FrameStatsGl
---@field num_bind_buffer? integer
---@field num_active_texture? integer
---@field num_bind_texture? integer
---@field num_bind_sampler? integer
---@field num_bind_image_texture? integer
---@field num_use_program? integer
---@field num_render_state? integer
---@field num_vertex_attrib_pointer? integer
---@field num_vertex_attrib_divisor? integer
---@field num_enable_vertex_attrib_array? integer
---@field num_disable_vertex_attrib_array? integer
---@field num_uniform? integer
---@field num_memory_barriers? integer

---@class gfx.FrameStatsD3d11Pass
---@field num_om_set_render_targets? integer
---@field num_clear_render_target_view? integer
---@field num_clear_depth_stencil_view? integer
---@field num_resolve_subresource? integer

---@class gfx.FrameStatsD3d11Pipeline
---@field num_rs_set_state? integer
---@field num_om_set_depth_stencil_state? integer
---@field num_om_set_blend_state? integer
---@field num_ia_set_primitive_topology? integer
---@field num_ia_set_input_layout? integer
---@field num_vs_set_shader? integer
---@field num_vs_set_constant_buffers? integer
---@field num_ps_set_shader? integer
---@field num_ps_set_constant_buffers? integer
---@field num_cs_set_shader? integer
---@field num_cs_set_constant_buffers? integer

---@class gfx.FrameStatsD3d11Bindings
---@field num_ia_set_vertex_buffers? integer
---@field num_ia_set_index_buffer? integer
---@field num_vs_set_shader_resources? integer
---@field num_vs_set_samplers? integer
---@field num_ps_set_shader_resources? integer
---@field num_ps_set_samplers? integer
---@field num_cs_set_shader_resources? integer
---@field num_cs_set_samplers? integer
---@field num_cs_set_unordered_access_views? integer

---@class gfx.FrameStatsD3d11Uniforms
---@field num_update_subresource? integer

---@class gfx.FrameStatsD3d11Draw
---@field num_draw_indexed_instanced? integer
---@field num_draw_indexed? integer
---@field num_draw_instanced? integer
---@field num_draw? integer

---@class gfx.FrameStatsD3d11
---@field pass? gfx.FrameStatsD3d11Pass
---@field pipeline? gfx.FrameStatsD3d11Pipeline
---@field bindings? gfx.FrameStatsD3d11Bindings
---@field uniforms? gfx.FrameStatsD3d11Uniforms
---@field draw? gfx.FrameStatsD3d11Draw
---@field num_map? integer
---@field num_unmap? integer

---@class gfx.FrameStatsMetalIdpool
---@field num_added? integer
---@field num_released? integer
---@field num_garbage_collected? integer

---@class gfx.FrameStatsMetalPipeline
---@field num_set_blend_color? integer
---@field num_set_cull_mode? integer
---@field num_set_front_facing_winding? integer
---@field num_set_stencil_reference_value? integer
---@field num_set_depth_bias? integer
---@field num_set_render_pipeline_state? integer
---@field num_set_depth_stencil_state? integer

---@class gfx.FrameStatsMetalBindings
---@field num_set_vertex_buffer? integer
---@field num_set_vertex_buffer_offset? integer
---@field num_skip_redundant_vertex_buffer? integer
---@field num_set_vertex_texture? integer
---@field num_skip_redundant_vertex_texture? integer
---@field num_set_vertex_sampler_state? integer
---@field num_skip_redundant_vertex_sampler_state? integer
---@field num_set_fragment_buffer? integer
---@field num_set_fragment_buffer_offset? integer
---@field num_skip_redundant_fragment_buffer? integer
---@field num_set_fragment_texture? integer
---@field num_skip_redundant_fragment_texture? integer
---@field num_set_fragment_sampler_state? integer
---@field num_skip_redundant_fragment_sampler_state? integer
---@field num_set_compute_buffer? integer
---@field num_set_compute_buffer_offset? integer
---@field num_skip_redundant_compute_buffer? integer
---@field num_set_compute_texture? integer
---@field num_skip_redundant_compute_texture? integer
---@field num_set_compute_sampler_state? integer
---@field num_skip_redundant_compute_sampler_state? integer

---@class gfx.FrameStatsMetalUniforms
---@field num_set_vertex_buffer_offset? integer
---@field num_set_fragment_buffer_offset? integer
---@field num_set_compute_buffer_offset? integer

---@class gfx.FrameStatsMetal
---@field idpool? gfx.FrameStatsMetalIdpool
---@field pipeline? gfx.FrameStatsMetalPipeline
---@field bindings? gfx.FrameStatsMetalBindings
---@field uniforms? gfx.FrameStatsMetalUniforms

---@class gfx.FrameStatsWgpuUniforms
---@field num_set_bindgroup? integer
---@field size_write_buffer? integer

---@class gfx.FrameStatsWgpuBindings
---@field num_set_vertex_buffer? integer
---@field num_skip_redundant_vertex_buffer? integer
---@field num_set_index_buffer? integer
---@field num_skip_redundant_index_buffer? integer
---@field num_create_bindgroup? integer
---@field num_discard_bindgroup? integer
---@field num_set_bindgroup? integer
---@field num_skip_redundant_bindgroup? integer
---@field num_bindgroup_cache_hits? integer
---@field num_bindgroup_cache_misses? integer
---@field num_bindgroup_cache_collisions? integer
---@field num_bindgroup_cache_invalidates? integer
---@field num_bindgroup_cache_hash_vs_key_mismatch? integer

---@class gfx.FrameStatsWgpu
---@field uniforms? gfx.FrameStatsWgpuUniforms
---@field bindings? gfx.FrameStatsWgpuBindings

---@class gfx.FrameStatsVk
---@field num_cmd_pipeline_barrier? integer
---@field num_allocate_memory? integer
---@field num_free_memory? integer
---@field size_allocate_memory? integer
---@field num_delete_queue_added? integer
---@field num_delete_queue_collected? integer
---@field num_cmd_copy_buffer? integer
---@field num_cmd_copy_buffer_to_image? integer
---@field num_cmd_set_descriptor_buffer_offsets? integer
---@field size_descriptor_buffer_writes? integer

---@class gfx.FrameResourceStats
---@field allocated? integer
---@field deallocated? integer
---@field inited? integer
---@field uninited? integer

---@class gfx.TotalResourceStats
---@field alive? integer
---@field free? integer
---@field allocated? integer
---@field deallocated? integer
---@field inited? integer
---@field uninited? integer

---@class gfx.TotalStats
---@field buffers? gfx.TotalResourceStats
---@field images? gfx.TotalResourceStats
---@field samplers? gfx.TotalResourceStats
---@field views? gfx.TotalResourceStats
---@field shaders? gfx.TotalResourceStats
---@field pipelines? gfx.TotalResourceStats

---@class gfx.FrameStats
---@field frame_index? integer
---@field num_passes? integer
---@field num_apply_viewport? integer
---@field num_apply_scissor_rect? integer
---@field num_apply_pipeline? integer
---@field num_apply_bindings? integer
---@field num_apply_uniforms? integer
---@field num_draw? integer
---@field num_draw_ex? integer
---@field num_dispatch? integer
---@field num_update_buffer? integer
---@field num_append_buffer? integer
---@field num_update_image? integer
---@field size_apply_uniforms? integer
---@field size_update_buffer? integer
---@field size_append_buffer? integer
---@field size_update_image? integer
---@field buffers? gfx.FrameResourceStats
---@field images? gfx.FrameResourceStats
---@field samplers? gfx.FrameResourceStats
---@field views? gfx.FrameResourceStats
---@field shaders? gfx.FrameResourceStats
---@field pipelines? gfx.FrameResourceStats
---@field gl? gfx.FrameStatsGl
---@field d3d11? gfx.FrameStatsD3d11
---@field metal? gfx.FrameStatsMetal
---@field wgpu? gfx.FrameStatsWgpu
---@field vk? gfx.FrameStatsVk

---@class gfx.Stats
---@field prev_frame? gfx.FrameStats
---@field cur_frame? gfx.FrameStats
---@field total? gfx.TotalStats

---@class gfx.EnvironmentDefaults
---@field color_format? gfx.PixelFormat
---@field depth_format? gfx.PixelFormat
---@field sample_count? integer

---@class gfx.MetalEnvironment
---@field device? lightuserdata?

---@class gfx.D3d11Environment
---@field device? lightuserdata?
---@field device_context? lightuserdata?

---@class gfx.WgpuEnvironment
---@field device? lightuserdata?

---@class gfx.VulkanEnvironment
---@field physical_device? lightuserdata?
---@field device? lightuserdata?
---@field queue? lightuserdata?
---@field queue_family_index? integer

---@class gfx.Environment
---@field defaults? gfx.EnvironmentDefaults
---@field metal? gfx.MetalEnvironment
---@field d3d11? gfx.D3d11Environment
---@field wgpu? gfx.WgpuEnvironment
---@field vulkan? gfx.VulkanEnvironment

---@class gfx.CommitListener
---@field func? any
---@field user_data? lightuserdata?

---@class gfx.Allocator
---@field alloc_fn? any
---@field free_fn? any
---@field user_data? lightuserdata?

---@class gfx.Logger
---@field func? any
---@field user_data? lightuserdata?

---@class gfx.D3d11Desc
---@field shader_debugging? boolean

---@class gfx.MetalDesc
---@field force_managed_storage_mode? boolean
---@field use_command_buffer_with_retained_references? boolean

---@class gfx.WgpuDesc
---@field disable_bindgroups_cache? boolean
---@field bindgroups_cache_size? integer

---@class gfx.VulkanDesc
---@field copy_staging_buffer_size? integer
---@field stream_staging_buffer_size? integer
---@field descriptor_buffer_size? integer

---@class gfx.Desc
---@field _start_canary? integer
---@field buffer_pool_size? integer
---@field image_pool_size? integer
---@field sampler_pool_size? integer
---@field shader_pool_size? integer
---@field pipeline_pool_size? integer
---@field view_pool_size? integer
---@field uniform_buffer_size? integer
---@field max_commit_listeners? integer
---@field disable_validation? boolean
---@field enforce_portable_limits? boolean
---@field d3d11? gfx.D3d11Desc
---@field metal? gfx.MetalDesc
---@field wgpu? gfx.WgpuDesc
---@field vulkan? gfx.VulkanDesc
---@field allocator? gfx.Allocator
---@field logger? gfx.Logger
---@field environment? gfx.Environment
---@field _end_canary? integer

---@class gfx.D3d11BufferInfo
---@field buf? lightuserdata?

---@class gfx.D3d11ImageInfo
---@field tex2d? lightuserdata?
---@field tex3d? lightuserdata?
---@field res? lightuserdata?

---@class gfx.D3d11SamplerInfo
---@field smp? lightuserdata?

---@class gfx.D3d11ShaderInfo
---@field cbufs? lightuserdata?[]
---@field vs? lightuserdata?
---@field fs? lightuserdata?

---@class gfx.D3d11PipelineInfo
---@field il? lightuserdata?
---@field rs? lightuserdata?
---@field dss? lightuserdata?
---@field bs? lightuserdata?

---@class gfx.D3d11ViewInfo
---@field srv? lightuserdata?
---@field uav? lightuserdata?
---@field rtv? lightuserdata?
---@field dsv? lightuserdata?

---@class gfx.MtlBufferInfo
---@field buf? lightuserdata?[]
---@field active_slot? integer

---@class gfx.MtlImageInfo
---@field tex? lightuserdata?[]
---@field active_slot? integer

---@class gfx.MtlSamplerInfo
---@field smp? lightuserdata?

---@class gfx.MtlShaderInfo
---@field vertex_lib? lightuserdata?
---@field fragment_lib? lightuserdata?
---@field vertex_func? lightuserdata?
---@field fragment_func? lightuserdata?

---@class gfx.MtlPipelineInfo
---@field rps? lightuserdata?
---@field dss? lightuserdata?

---@class gfx.WgpuBufferInfo
---@field buf? lightuserdata?

---@class gfx.WgpuImageInfo
---@field tex? lightuserdata?

---@class gfx.WgpuSamplerInfo
---@field smp? lightuserdata?

---@class gfx.WgpuShaderInfo
---@field vs_mod? lightuserdata?
---@field fs_mod? lightuserdata?
---@field bgl? lightuserdata?

---@class gfx.WgpuPipelineInfo
---@field render_pipeline? lightuserdata?
---@field compute_pipeline? lightuserdata?

---@class gfx.WgpuViewInfo
---@field view? lightuserdata?

---@class gfx.GlBufferInfo
---@field buf? integer[]
---@field active_slot? integer

---@class gfx.GlImageInfo
---@field tex? integer[]
---@field tex_target? integer
---@field active_slot? integer

---@class gfx.GlSamplerInfo
---@field smp? integer

---@class gfx.GlShaderInfo
---@field prog? integer

---@class gfx.GlViewInfo
---@field tex_view? integer[]
---@field msaa_render_buffer? integer
---@field msaa_resolve_frame_buffer? integer

---@param desc gfx.Desc
function gfx.setup(desc) end

function gfx.shutdown() end

---@return boolean
function gfx.isvalid() end

function gfx.reset_state_cache() end

---@param name string
function gfx.push_debug_group(name) end

function gfx.pop_debug_group() end

---@param listener gfx.CommitListener
---@return boolean
function gfx.add_commit_listener(listener) end

---@param listener gfx.CommitListener
---@return boolean
function gfx.remove_commit_listener(listener) end

---@param desc gfx.BufferDesc
---@return gfx.Buffer
function gfx.make_buffer(desc) end

---@param desc gfx.ImageDesc
---@return gfx.Image
function gfx.make_image(desc) end

---@param desc gfx.SamplerDesc
---@return gfx.Sampler
function gfx.make_sampler(desc) end

---@param desc gfx.ShaderDesc
---@return gfx.Shader
function gfx.make_shader(desc) end

---@param desc gfx.PipelineDesc
---@return gfx.Pipeline
function gfx.make_pipeline(desc) end

---@param desc gfx.ViewDesc
---@return gfx.View
function gfx.make_view(desc) end

---@param buf gfx.Buffer
function gfx.destroy_buffer(buf) end

---@param img gfx.Image
function gfx.destroy_image(img) end

---@param smp gfx.Sampler
function gfx.destroy_sampler(smp) end

---@param shd gfx.Shader
function gfx.destroy_shader(shd) end

---@param pip gfx.Pipeline
function gfx.destroy_pipeline(pip) end

---@param view gfx.View
function gfx.destroy_view(view) end

---@param buf gfx.Buffer
---@param data gfx.Range
function gfx.update_buffer(buf, data) end

---@param img gfx.Image
---@param data gfx.ImageData
function gfx.update_image(img, data) end

---@param buf gfx.Buffer
---@param data gfx.Range
---@return integer
function gfx.append_buffer(buf, data) end

---@param buf gfx.Buffer
---@return boolean
function gfx.query_buffer_overflow(buf) end

---@param buf gfx.Buffer
---@param size integer
---@return boolean
function gfx.query_buffer_will_overflow(buf, size) end

---@param pass gfx.Pass
function gfx.begin_pass(pass) end

---@param x integer
---@param y integer
---@param width integer
---@param height integer
---@param origin_top_left boolean
function gfx.apply_viewport(x, y, width, height, origin_top_left) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param origin_top_left boolean
function gfx.apply_viewportf(x, y, width, height, origin_top_left) end

---@param x integer
---@param y integer
---@param width integer
---@param height integer
---@param origin_top_left boolean
function gfx.apply_scissor_rect(x, y, width, height, origin_top_left) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param origin_top_left boolean
function gfx.apply_scissor_rectf(x, y, width, height, origin_top_left) end

---@param pip gfx.Pipeline
function gfx.apply_pipeline(pip) end

---@param bindings gfx.Bindings
function gfx.apply_bindings(bindings) end

---@param ub_slot integer
---@param data gfx.Range
function gfx.apply_uniforms(ub_slot, data) end

---@param base_element integer
---@param num_elements integer
---@param num_instances integer
function gfx.draw(base_element, num_elements, num_instances) end

---@param base_element integer
---@param num_elements integer
---@param num_instances integer
---@param base_vertex integer
---@param base_instance integer
function gfx.draw_ex(base_element, num_elements, num_instances, base_vertex, base_instance) end

---@param num_groups_x integer
---@param num_groups_y integer
---@param num_groups_z integer
function gfx.dispatch(num_groups_x, num_groups_y, num_groups_z) end

function gfx.end_pass() end

function gfx.commit() end

---@return gfx.Desc
function gfx.query_desc() end

---@return gfx.Backend
function gfx.query_backend() end

---@return gfx.Features
function gfx.query_features() end

---@return gfx.Limits
function gfx.query_limits() end

---@param fmt gfx.PixelFormat
---@return gfx.PixelformatInfo
function gfx.query_pixelformat(fmt) end

---@param fmt gfx.PixelFormat
---@param width integer
---@param row_align_bytes integer
---@return integer
function gfx.query_row_pitch(fmt, width, row_align_bytes) end

---@param fmt gfx.PixelFormat
---@param width integer
---@param height integer
---@param row_align_bytes integer
---@return integer
function gfx.query_surface_pitch(fmt, width, height, row_align_bytes) end

---@param buf gfx.Buffer
---@return gfx.ResourceState
function gfx.query_buffer_state(buf) end

---@param img gfx.Image
---@return gfx.ResourceState
function gfx.query_image_state(img) end

---@param smp gfx.Sampler
---@return gfx.ResourceState
function gfx.query_sampler_state(smp) end

---@param shd gfx.Shader
---@return gfx.ResourceState
function gfx.query_shader_state(shd) end

---@param pip gfx.Pipeline
---@return gfx.ResourceState
function gfx.query_pipeline_state(pip) end

---@param view gfx.View
---@return gfx.ResourceState
function gfx.query_view_state(view) end

---@param buf gfx.Buffer
---@return gfx.BufferInfo
function gfx.query_buffer_info(buf) end

---@param img gfx.Image
---@return gfx.ImageInfo
function gfx.query_image_info(img) end

---@param smp gfx.Sampler
---@return gfx.SamplerInfo
function gfx.query_sampler_info(smp) end

---@param shd gfx.Shader
---@return gfx.ShaderInfo
function gfx.query_shader_info(shd) end

---@param pip gfx.Pipeline
---@return gfx.PipelineInfo
function gfx.query_pipeline_info(pip) end

---@param view gfx.View
---@return gfx.ViewInfo
function gfx.query_view_info(view) end

---@param buf gfx.Buffer
---@return gfx.BufferDesc
function gfx.query_buffer_desc(buf) end

---@param img gfx.Image
---@return gfx.ImageDesc
function gfx.query_image_desc(img) end

---@param smp gfx.Sampler
---@return gfx.SamplerDesc
function gfx.query_sampler_desc(smp) end

---@param shd gfx.Shader
---@return gfx.ShaderDesc
function gfx.query_shader_desc(shd) end

---@param pip gfx.Pipeline
---@return gfx.PipelineDesc
function gfx.query_pipeline_desc(pip) end

---@param view gfx.View
---@return gfx.ViewDesc
function gfx.query_view_desc(view) end

---@param desc gfx.BufferDesc
---@return gfx.BufferDesc
function gfx.query_buffer_defaults(desc) end

---@param desc gfx.ImageDesc
---@return gfx.ImageDesc
function gfx.query_image_defaults(desc) end

---@param desc gfx.SamplerDesc
---@return gfx.SamplerDesc
function gfx.query_sampler_defaults(desc) end

---@param desc gfx.ShaderDesc
---@return gfx.ShaderDesc
function gfx.query_shader_defaults(desc) end

---@param desc gfx.PipelineDesc
---@return gfx.PipelineDesc
function gfx.query_pipeline_defaults(desc) end

---@param desc gfx.ViewDesc
---@return gfx.ViewDesc
function gfx.query_view_defaults(desc) end

---@param buf gfx.Buffer
---@return integer
function gfx.query_buffer_size(buf) end

---@param buf gfx.Buffer
---@return gfx.BufferUsage
function gfx.query_buffer_usage(buf) end

---@param img gfx.Image
---@return gfx.ImageType
function gfx.query_image_type(img) end

---@param img gfx.Image
---@return integer
function gfx.query_image_width(img) end

---@param img gfx.Image
---@return integer
function gfx.query_image_height(img) end

---@param img gfx.Image
---@return integer
function gfx.query_image_num_slices(img) end

---@param img gfx.Image
---@return integer
function gfx.query_image_num_mipmaps(img) end

---@param img gfx.Image
---@return gfx.PixelFormat
function gfx.query_image_pixelformat(img) end

---@param img gfx.Image
---@return gfx.ImageUsage
function gfx.query_image_usage(img) end

---@param img gfx.Image
---@return integer
function gfx.query_image_sample_count(img) end

---@param view gfx.View
---@return gfx.ViewType
function gfx.query_view_type(view) end

---@param view gfx.View
---@return gfx.Image
function gfx.query_view_image(view) end

---@param view gfx.View
---@return gfx.Buffer
function gfx.query_view_buffer(view) end

---@return gfx.Buffer
function gfx.alloc_buffer() end

---@return gfx.Image
function gfx.alloc_image() end

---@return gfx.Sampler
function gfx.alloc_sampler() end

---@return gfx.Shader
function gfx.alloc_shader() end

---@return gfx.Pipeline
function gfx.alloc_pipeline() end

---@return gfx.View
function gfx.alloc_view() end

---@param buf gfx.Buffer
function gfx.dealloc_buffer(buf) end

---@param img gfx.Image
function gfx.dealloc_image(img) end

---@param smp gfx.Sampler
function gfx.dealloc_sampler(smp) end

---@param shd gfx.Shader
function gfx.dealloc_shader(shd) end

---@param pip gfx.Pipeline
function gfx.dealloc_pipeline(pip) end

---@param view gfx.View
function gfx.dealloc_view(view) end

---@param buf gfx.Buffer
---@param desc gfx.BufferDesc
function gfx.init_buffer(buf, desc) end

---@param img gfx.Image
---@param desc gfx.ImageDesc
function gfx.init_image(img, desc) end

---@param smg gfx.Sampler
---@param desc gfx.SamplerDesc
function gfx.init_sampler(smg, desc) end

---@param shd gfx.Shader
---@param desc gfx.ShaderDesc
function gfx.init_shader(shd, desc) end

---@param pip gfx.Pipeline
---@param desc gfx.PipelineDesc
function gfx.init_pipeline(pip, desc) end

---@param view gfx.View
---@param desc gfx.ViewDesc
function gfx.init_view(view, desc) end

---@param buf gfx.Buffer
function gfx.uninit_buffer(buf) end

---@param img gfx.Image
function gfx.uninit_image(img) end

---@param smp gfx.Sampler
function gfx.uninit_sampler(smp) end

---@param shd gfx.Shader
function gfx.uninit_shader(shd) end

---@param pip gfx.Pipeline
function gfx.uninit_pipeline(pip) end

---@param view gfx.View
function gfx.uninit_view(view) end

---@param buf gfx.Buffer
function gfx.fail_buffer(buf) end

---@param img gfx.Image
function gfx.fail_image(img) end

---@param smp gfx.Sampler
function gfx.fail_sampler(smp) end

---@param shd gfx.Shader
function gfx.fail_shader(shd) end

---@param pip gfx.Pipeline
function gfx.fail_pipeline(pip) end

---@param view gfx.View
function gfx.fail_view(view) end

function gfx.enable_stats() end

function gfx.disable_stats() end

---@return boolean
function gfx.stats_enabled() end

---@return gfx.Stats
function gfx.query_stats() end

---@return lightuserdata?
function gfx.d3d11_device() end

---@return lightuserdata?
function gfx.d3d11_device_context() end

---@param buf gfx.Buffer
---@return gfx.D3d11BufferInfo
function gfx.d3d11_query_buffer_info(buf) end

---@param img gfx.Image
---@return gfx.D3d11ImageInfo
function gfx.d3d11_query_image_info(img) end

---@param smp gfx.Sampler
---@return gfx.D3d11SamplerInfo
function gfx.d3d11_query_sampler_info(smp) end

---@param shd gfx.Shader
---@return gfx.D3d11ShaderInfo
function gfx.d3d11_query_shader_info(shd) end

---@param pip gfx.Pipeline
---@return gfx.D3d11PipelineInfo
function gfx.d3d11_query_pipeline_info(pip) end

---@param view gfx.View
---@return gfx.D3d11ViewInfo
function gfx.d3d11_query_view_info(view) end

---@return lightuserdata?
function gfx.mtl_device() end

---@return lightuserdata?
function gfx.mtl_render_command_encoder() end

---@return lightuserdata?
function gfx.mtl_compute_command_encoder() end

---@param buf gfx.Buffer
---@return gfx.MtlBufferInfo
function gfx.mtl_query_buffer_info(buf) end

---@param img gfx.Image
---@return gfx.MtlImageInfo
function gfx.mtl_query_image_info(img) end

---@param smp gfx.Sampler
---@return gfx.MtlSamplerInfo
function gfx.mtl_query_sampler_info(smp) end

---@param shd gfx.Shader
---@return gfx.MtlShaderInfo
function gfx.mtl_query_shader_info(shd) end

---@param pip gfx.Pipeline
---@return gfx.MtlPipelineInfo
function gfx.mtl_query_pipeline_info(pip) end

---@return lightuserdata?
function gfx.wgpu_device() end

---@return lightuserdata?
function gfx.wgpu_queue() end

---@return lightuserdata?
function gfx.wgpu_command_encoder() end

---@return lightuserdata?
function gfx.wgpu_render_pass_encoder() end

---@return lightuserdata?
function gfx.wgpu_compute_pass_encoder() end

---@param buf gfx.Buffer
---@return gfx.WgpuBufferInfo
function gfx.wgpu_query_buffer_info(buf) end

---@param img gfx.Image
---@return gfx.WgpuImageInfo
function gfx.wgpu_query_image_info(img) end

---@param smp gfx.Sampler
---@return gfx.WgpuSamplerInfo
function gfx.wgpu_query_sampler_info(smp) end

---@param shd gfx.Shader
---@return gfx.WgpuShaderInfo
function gfx.wgpu_query_shader_info(shd) end

---@param pip gfx.Pipeline
---@return gfx.WgpuPipelineInfo
function gfx.wgpu_query_pipeline_info(pip) end

---@param view gfx.View
---@return gfx.WgpuViewInfo
function gfx.wgpu_query_view_info(view) end

---@param buf gfx.Buffer
---@return gfx.GlBufferInfo
function gfx.gl_query_buffer_info(buf) end

---@param img gfx.Image
---@return gfx.GlImageInfo
function gfx.gl_query_image_info(img) end

---@param smp gfx.Sampler
---@return gfx.GlSamplerInfo
function gfx.gl_query_sampler_info(smp) end

---@param shd gfx.Shader
---@return gfx.GlShaderInfo
function gfx.gl_query_shader_info(shd) end

---@param view gfx.View
---@return gfx.GlViewInfo
function gfx.gl_query_view_info(view) end

return gfx